// Authoring source only. Runtime consumes checkpoints.json/contracts.json.
// | marks intentional word boundaries; generation never invents learner text.
const line=(speaker,text,pinyin,translation,note)=>({speaker,text,pinyin,translation,note});
const q=(prompt,options,answer,evidence,explanation)=>({prompt,options,answer,evidence,explanation});
const reading=(unit,title,presentation,setup,grammarIds,lines,questions,tips,glosses={})=>({unit,title,presentation,setup,grammarIds,lines,questions,tips,glosses});
export const denseSpecs=[
 reading(11,'Two drinks, two different orders','dialogue','Read a café conversation. Keep track of which customer wants each drink and where each will drink it.',
 ['u11-cup','u11-hot','u11-size','u11-here','u11-takeout'],[
 line('Lin','我|想|喝|熱|茶|。|你|呢|？','Wǒ xiǎng hē rè chá. Nǐ ne?','I feel like hot tea. How about you?','想 introduces a wish. The short follow-up 你呢 asks for the other person’s drink preference, not agreement with Lin’s choice.'),
 line('Mei','我|要|咖啡|，|不|要|茶|。','Wǒ yào kāfēi, bú yào chá.','I want coffee, not tea.','不要 negates what Mei wants. This contrast assigns coffee to Mei and tea to Lin; it does not cancel Lin’s order.'),
 line('Staff','熱|咖啡|，|大|杯|還是|中|杯|？','Rè kāfēi, dà bēi háishì zhōng bēi?','Hot coffee—large or medium?','還是 presents two sizes inside a question. 咖啡 is already understood after each size, so it is not repeated.'),
 line('Mei','中|杯|，|謝謝|。|我|的|咖啡|內用|。','Zhōng bēi, xièxie. Wǒ de kāfēi nèiyòng.','Medium, thanks. My coffee is for here.','The size answers the preceding question. 內用 states the service choice for Mei’s coffee; it does not apply to Lin’s tea.'),
 line('Staff','你|的|茶|也|要|中|杯|嗎|？','Nǐ de chá yě yào zhōng bēi ma?','Would you also like your tea medium?','的 links the tea to its customer. 也 asks whether the size is shared; it does not say that the drinks are the same.'),
 line('Lin','不|，|我|要|大|杯|。|我|的|茶|外帶|。','Bù, wǒ yào dà bēi. Wǒ de chá wàidài.','No, I want large. My tea is to go.','The first sentence rejects the proposed size. 外帶 specifies takeout for Lin’s tea, without changing Mei’s for-here order.'),
 line('Staff','好|的|，|一|杯|大|杯|熱|茶|外帶|，|一|杯|中|杯|熱|咖啡|內用|。','Hǎo de, yì bēi dà bēi rè chá wàidài, yì bēi zhōng bēi rè kāfēi nèiyòng.','Okay: one large hot tea to go and one medium hot coffee for here.','一杯 counts each drink; 大杯 and 中杯 specify size. Match each service choice to its own drink, not to the whole order.'),
 line('Lin','謝謝|。|明天|早上|我們|一起|喝|茶|，|好不好|？','Xièxie. Míngtiān zǎoshang wǒmen yìqǐ hē chá, hǎo bù hǎo?','Thanks. Shall we have tea together tomorrow morning?','明天早上 sets a new time. 好不好 makes this an invitation, so the passage does not yet establish that Mei accepts it.')
 ],[
 q('Which complete order belongs to Mei?',['Large hot tea to go','Medium hot coffee for here','Medium tea for here','Large coffee to go'],1,[1,3,6],'Mei chooses coffee, then medium and for here. The staff’s summary confirms all three details.'),
 q('What does Lin correct?',['The coffee temperature','Who is paying','The proposed tea size','Tomorrow’s time'],2,[4,5],'The staff suggests medium tea; Lin answers no and chooses large. Lin does not reject the tea itself.'),
 q('Do both customers take their drinks away?',['Yes, both are takeout','The passage never mentions this','Only Mei takes hers away','No: Lin takes tea away; Mei stays'],3,[3,5,6],'Mei says she will drink here and Lin says takeout. The final order retains that difference.'),
 q('What is still only a suggestion?',['Having tea together tomorrow morning','Ordering hot tea today','Making the coffee medium','Serving the coffee for here'],0,[7],'The last line asks for agreement about tomorrow. No reply accepting that invitation appears.')
 ],['Track each speaker’s order separately; a short answer inherits the topic of the previous question.','A final invitation is not a confirmed event unless somebody accepts it.']),
 reading(14,'Which phone is actually for sale?','dialogue','At a phone shop, a customer compares two devices. Read beyond the prices before deciding what they can buy.',
 ['u14-phones','u14-de-ones','u14-capability','u14-why','u14-too'],[
 line('Customer','老闆|，|請問|，|這|兩|支|手機|都|賣|嗎|？','Lǎobǎn, qǐngwèn, zhè liǎng zhī shǒujī dōu mài ma?','Excuse me, are both of these phones for sale?','兩支 counts phones and 都 asks about both devices. A question is not evidence that both are available to buy.'),
 line('Owner','新|的|賣|，|舊|的|不|賣|。|舊|的|是|我|的|。','Xīn de mài, jiù de bú mài. Jiù de shì wǒ de.','The new one is for sale; the old one isn’t. The old one is mine.','With 手機 understood, 新的 and 舊的 identify the two phones. The owner draws a clear distinction between sale stock and personal property.'),
 line('Customer','新|的|多少|錢|？|我|想|買|一|支|便宜|的|手機|。','Xīn de duōshǎo qián? Wǒ xiǎng mǎi yì zhī piányí de shǒujī.','How much is the new one? I want to buy an inexpensive phone.','多少錢 asks for the price. Wanting an inexpensive phone is the customer’s preference, not proof that this new phone is inexpensive.'),
 line('Owner','這|支|新|手機|五|千|塊|。|能|上網|，|也|能|照相|。','Zhè zhī xīn shǒujī wǔ qiān kuài. Néng shàngwǎng, yě néng zhàoxiàng.','This new phone is five thousand dollars. It can go online and take photos.','能 describes the device’s capabilities. The understood subject of the second sentence remains the new phone.'),
 line('Customer','五|千|塊|太|貴|了|！|舊|的|能|上網|嗎|？','Wǔ qiān kuài tài guì le! Jiù de néng shàngwǎng ma?','Five thousand is too expensive! Can the old one go online?','太…了 expresses an excessive degree, not a completed purchase. The following question switches attention back to the old phone.'),
 line('Owner','能|。|我|很|喜歡|這|支|舊|手機|。','Néng. Wǒ hěn xǐhuān zhè zhī jiù shǒujī.','Yes. I really like this old phone.','能 answers the capability question by itself. Liking the old phone helps explain the owner’s attachment but does not make it available for sale.'),
 line('Customer','你|為什麼|不|賣|舊|的|？','Nǐ wèishénme bú mài jiù de?','Why won’t you sell the old one?','為什麼 asks for a reason and appears before 不賣. 舊的 still refers to the phone introduced near the beginning.'),
 line('Owner','我|也|要|上網|！|我|不|想|買|新|的|手機|。','Wǒ yě yào shàngwǎng! Wǒ bù xiǎng mǎi xīn de shǒujī.','I need to go online too! I don’t want to buy a new phone.','也 connects the owner’s need with the customer’s interest in internet access. Keeping the old phone avoids buying another; no purchase is confirmed.')
 ],[
 q('Which phone is available to buy?',['Only the new one','Only the old one','Both phones','Neither phone'],0,[1],'The owner explicitly sells the new one but not the old one. Both are discussed, but only one is for sale.'),
 q('Which statement about internet access is supported?',['Only the old phone can go online','Neither can go online','Only the new phone can go online','Both can go online'],3,[3,4,5],'The new phone’s features include internet access; the owner then answers yes about the old one.'),
 q('Why does the owner keep the old phone?',['It belongs to the customer','The owner also needs a phone for internet use','It costs five thousand','It cannot take photos'],1,[1,7],'The old phone belongs to the owner, who explains a personal need to use it online.'),
 q('What can we conclude about a purchase?',['The customer buys both','The owner gives away the old one','No purchase is confirmed','The customer pays five thousand'],2,[2,4,7],'The customer wants a cheap phone and objects to the price, but the conversation contains no agreement to buy.')
 ],['Keep ownership, capability and availability separate; a working object need not be for sale.','With 的, recover the omitted noun from the conversation rather than translating 的 alone.']),
 reading(17,'The dinner chat has a complication','messages','A LINE-style chat between two friends planning dinner. Follow the recommendation, the concern and the eventual choice.',
 ['u17-heard','u17-recommend','u16-result','u16-performance','u16-contrast'],[
 line('Mei','你|知道|那|家|有名|的|小吃|店|嗎|？|聽說|小籠包|很|好吃|。','Nǐ zhīdào nà jiā yǒumíng de xiǎochī diàn ma? Tīngshuō xiǎolóngbāo hěn hǎochī.','Do you know that famous snack shop? I hear its soup dumplings are delicious.','聽說 marks a report from others, not Mei’s own experience. 家 counts a shop, while 小籠包 is the dish being recommended.'),
 line('Lin','知道|。|我|昨天|去|那裡|吃|臭豆腐|，|有一點|辣|。','Zhīdào. Wǒ zuótiān qù nàlǐ chī chòudòufu, yǒuyìdiǎn là.','Yes. I went there for stinky tofu yesterday; it was a little spicy.','昨天 places the visit in the past without requiring 了. The mild criticism 有一點辣 describes the tofu, not every dish at the shop.'),
 line('Mei','我|怕|辣|，|所以|不|想|吃|臭豆腐|。','Wǒ pà là, suǒyǐ bù xiǎng chī chòudòufu.','I’m sensitive to spicy food, so I don’t want the stinky tofu.','所以 links a reason to its consequence. Mei rejects one dish because of spice; she has not rejected the entire shop.'),
 line('Lin','那|家|店|的|小籠包|不|辣|，|你|一定|要|吃|。','Nà jiā diàn de xiǎolóngbāo bú là, nǐ yídìng yào chī.','The shop’s soup dumplings aren’t spicy. You really should try them.','一定要 makes a strong recommendation here. The first clause addresses Mei’s concern and keeps the shop a possible dinner choice.'),
 line('Mei','太好了|！|我|要|吃|小籠包|。|你|呢|？','Tài hǎo le! Wǒ yào chī xiǎolóngbāo. Nǐ ne?','Great! I’ll have soup dumplings. How about you?','The response accepts the suitable dish. 你呢 hands the same food-choice question back to Lin rather than asking about Lin’s ability to cook.'),
 line('Lin','我|想|吃|牛肉|麵|，|也|想|喝|湯|。','Wǒ xiǎng chī niúròu miàn, yě xiǎng hē tāng.','I’d like beef noodles and some soup.','想 states Lin’s choices. 也 adds a second desire for the same speaker; the friends do not have to order identical food.'),
 line('Mei','你|自己|做飯|做|得|不錯|，|為什麼|今天|不|自己|做|？','Nǐ zìjǐ zuòfàn zuò de búcuò, wèishénme jīntiān bù zìjǐ zuò?','You cook pretty well yourself. Why aren’t you cooking today?','做飯做得 repeats the verb before a performance comment. The final 做 omits the understood meal-making context, not a new skill.'),
 line('Lin','我|喜歡|做飯|，|可是|今天|想|和|你|一起|吃|。|我們|晚上|去|吧|！','Wǒ xǐhuān zuòfàn, kěshì jīntiān xiǎng hé nǐ yìqǐ chī. Wǒmen wǎnshang qù ba!','I like cooking, but today I want to eat with you. Let’s go this evening!','可是 contrasts a general preference with today’s wish. The social reason, not poor cooking ability, motivates the evening outing.')
 ],[
 q('Why does Mei reject the tofu?',['It is too expensive','The shop is closed','She is sensitive to spicy food','Lin has never tried it'],2,[1,2],'Lin calls the tofu a little spicy; Mei then explains that she is sensitive to spice.'),
 q('Which pairing matches their choices?',['Mei: dumplings; Lin: beef noodles and soup','Mei: tofu; Lin: dumplings','Both: tofu','Both: only soup'],0,[4,5],'Mei accepts the dumplings, while Lin names beef noodles and soup. The agreement is about eating together, not the same order.'),
 q('Which claim begins as second-hand information?',['Lin ate tofu yesterday','Mei dislikes spicy food','Lin cooks well','The shop’s dumplings are delicious'],3,[0],'Mei introduces the dumpling recommendation with 聽說, explicitly presenting it as something she has heard.'),
 q('Why does Lin want to go out despite cooking well?',['To learn to make noodles','To eat together with Mei','Because the kitchen is broken','Because all the food is free'],1,[6,7],'Mei acknowledges Lin’s cooking skill. Lin answers that the point today is sharing a meal with Mei.')
 ],['A concern about one dish need not cancel a whole plan. Track how the next message solves that concern.','Distinguish reported information, first-hand experience and a present preference.']),
 reading(20,'Find the classroom, not the pool','notice','Read a campus information card and a visitor’s question. The floor and the landmark both matter.',
 ['u20-floor','u20-front-back','u20-beside','u20-correction','u18-location-action'],[
 line('Campus card','這|棟|大樓|在|圖書館|旁邊|，|不|在|宿舍|旁邊|。','Zhè dòng dàlóu zài túshūguǎn pángbiān, bú zài sùshè pángbiān.','This building is beside the library, not beside the dormitory.','棟 counts an entire building. The two location clauses distinguish the correct landmark from a plausible but wrong one.'),
 line('Campus card','中文|教室|在|三|樓|，|英文|教室|在|二|樓|。','Zhōngwén jiàoshì zài sān lóu, Yīngwén jiàoshì zài èr lóu.','The Chinese classroom is on the third floor; the English classroom is on the second.','Floor numbers come directly before 樓. Keep each subject with its own floor rather than treating the two rooms as one place.'),
 line('Campus card','中文|老師|也|在|三|樓|，|現在|在|教室|裡面|。','Zhōngwén lǎoshī yě zài sān lóu, xiànzài zài jiàoshì lǐmiàn.','The Chinese teacher is also on the third floor, inside the classroom now.','也 adds the teacher to the location already established for Chinese class. 現在 describes current whereabouts, not a permanent room assignment.'),
 line('Campus card','大樓|前面|有|一|家|商店|，|後面|有|游泳池|。','Dàlóu qiánmiàn yǒu yì jiā shāngdiàn, hòumiàn yǒu yóuyǒngchí.','There is a shop in front of the building and a swimming pool behind it.','The building remains the reference landmark in both clauses. 前面 and 後面 identify opposite sides, not different floors.'),
 line('Campus card','商店|裡面|有|茶|和|咖啡|，|也|有|包子|。','Shāngdiàn lǐmiàn yǒu chá hé kāfēi, yě yǒu bāozi.','Inside the shop there are tea, coffee and buns.','裡面 now refers to the shop rather than the classroom building. 有 lists what is available without saying anything about prices.'),
 line('Visitor','我|現在|在|游泳池|旁邊|。|中文|教室|在|這裡|嗎|？','Wǒ xiànzài zài yóuyǒngchí pángbiān. Zhōngwén jiàoshì zài zhèlǐ ma?','I’m beside the pool now. Is the Chinese classroom here?','The visitor gives a current location, then asks a question. Do not mistake that question for a correct statement about the classroom.'),
 line('Reply','不|是|在|這裡|，|是|在|圖書館|旁邊|的|大樓|三|樓|。','Bú shì zài zhèlǐ, shì zài túshūguǎn pángbiān de dàlóu sān lóu.','Not here—it’s on the third floor of the building beside the library.','不是…是… corrects the assumption. The location modifier identifies the building first; 三樓 then identifies the floor inside it.'),
 line('Reply','你|的|朋友|也|在|那裡|上課|。|歡迎|你|來|！','Nǐ de péngyǒu yě zài nàlǐ shàngkè. Huānyíng nǐ lái!','Your friend also has class there. You’re welcome to come!','那裡 refers back to the classroom just located, not the pool. 在…上課 places the activity at that already-established location.')
 ],[
 q('Where should the visitor look for the Chinese classroom?',['Second floor beside the dormitory','Third floor of the building beside the library','Inside the shop','Beside the pool'],1,[0,1,6],'The card and correction agree: choose the library-side building, then its third floor.'),
 q('Which place is on the opposite side of the building from the shop?',['The English classroom','The dormitory','The teachers’ classroom','The swimming pool'],3,[3],'The shop is in front and the pool behind. Both positions use the same building as their landmark.'),
 q('What does “there” in the final reply point back to?',['The Chinese classroom just identified','The inside of the shop','The dormitory','The swimming pool'],0,[6,7],'The reply first identifies the correct classroom; the following 那裡 refers to that location.'),
 q('What information is NOT provided by the card?',['The English classroom’s floor','The shop’s position','The price of a bun','The building’s landmark'],2,[0,1,3,4],'The card lists buns inside the shop but gives no price. Location and availability do not imply a cost.')
 ],['Follow the reference landmark each time you see front, back or beside.','Read a correction as a replacement for the mistaken claim, not as a second equally valid location.']),
 reading(23,'Is there time before calligraphy?','schedule','Read Mei’s afternoon schedule and the messages below it. Find a meeting time that fits, without assuming permission has been granted.',
 ['u21-clock-time','u21-from-to-time','u22-half-time','u23-permission-questions'],[
 line('12:00–12:30','從|中午|十|二|點|到|十|二|點|半|，|我|和|朋友|吃|午餐|。','Cóng zhōngwǔ shí’èr diǎn dào shí’èr diǎn bàn, wǒ hé péngyǒu chī wǔcān.','From noon to twelve thirty, I have lunch with a friend.','從…到… marks the two ends of a time range. 半 means half past the stated hour, not half of the whole lunch period.'),
 line('13:00–14:30','下午|一|點|有|中文|課|，|兩|點|半|下課|。','Xiàwǔ yì diǎn yǒu Zhōngwén kè, liǎng diǎn bàn xiàkè.','Chinese class is at one in the afternoon; it finishes at two thirty.','The second time is the end of Chinese class. 一點 is a clock reading here, not the later quantity expression meaning a little.'),
 line('15:00–16:00','書法|課|三|點|開始|，|四|點|結束|。','Shūfǎ kè sān diǎn kāishǐ, sì diǎn jiéshù.','Calligraphy class starts at three and ends at four.','開始 and 結束 label the two boundaries explicitly. This leaves a gap after Chinese class rather than two overlapping classes.'),
 line('After 16:00','四|點|我|有事|，|不|能|和|你|見面|。','Sì diǎn wǒ yǒushì, bù néng hé nǐ jiànmiàn.','I have something to do at four and can’t meet you then.','有事 says the speaker is occupied without naming the task. The end of a class does not automatically mean the person is free.'),
 line('Lin · message','兩|點|四|十|分|在|教室|外面|見面|，|好不好|？','Liǎng diǎn sìshí fēn zài jiàoshì wàimiàn jiànmiàn, hǎo bù hǎo?','Shall we meet outside the classroom at two forty?','Time comes before place and the meeting action. Forty minutes past two falls after the first class and before the next one.'),
 line('Mei · reply','沒問題|。|三|點|我|有|書法|課|。','Méi wèntí. Sān diǎn wǒ yǒu shūfǎ kè.','No problem. I have calligraphy at three.','沒問題 accepts the proposed meeting. The following reminder limits the available time; it does not cancel the acceptance.'),
 line('Lin · message','書法|很|有意思|。|我|可不可以|去|看|你|寫字|？','Shūfǎ hěn yǒuyìsi. Wǒ kě bù kěyǐ qù kàn nǐ xiězì?','Calligraphy is interesting. May I come watch you write?','可不可以 asks permission rather than physical ability. Interest in the class alone does not authorize a visit.'),
 line('Mei · reply','等一下|，|我|問|老師|。','Děng yíxià, wǒ wèn lǎoshī.','Wait a moment; I’ll ask the teacher.','Mei postpones the answer and names whom she will ask. This is neither a refusal nor confirmation that Lin may enter the class.')
 ],[
 q('Which suggested time fits between the two classes?',['13:40','16:00','14:40','15:40'],2,[1,2,4,5],'Chinese ends at 14:30 and calligraphy starts at 15:00. The proposed 14:40 meeting lies inside that gap.'),
 q('How much time is there from the agreed meeting to calligraphy?',['20 minutes','40 minutes','One hour','Ten minutes'],0,[2,4,5],'They agree on 14:40; calligraphy begins at 15:00, leaving twenty minutes.'),
 q('Can Lin definitely attend the calligraphy class?',['Yes, Mei has already obtained permission','No, visitors are always forbidden','Yes, because he is interested','Not yet established; Mei will ask the teacher'],3,[6,7],'Lin asks permission and Mei says she will ask the teacher. The teacher’s answer is not in the passage.'),
 q('Why not simply meet at four?',['Chinese class starts then','Mei says she has something to do','Lunch lasts until four','The classroom is closed'],1,[3],'The schedule explicitly says Mei is occupied at four, even though calligraphy has ended.')
 ],['Compare the end of one event with the start of the next, then check notes for extra restrictions.','A request and a promise to ask are not the same as permission.'],{'一點':{pinyin:'yì diǎn',meaning:'one o’clock',note:'The already-taught clock use of 點, not the later quantity expression.'}}),
 reading(26,'The Saturday plan changes','messages','Read a LINE-style exchange about a day off. Separate the first idea from the plan both people finally accept.',
 ['u26-dasuan-plan','u26-buxing-feasibility','u25-bi-comparison','u24-gen-company'],[
 line('Lin','這|個|星期|六|放假|，|你|打算|做|什麼|？','Zhè ge xīngqíliù fàngjià, nǐ dǎsuàn zuò shénme?','We have this Saturday off. What are you planning to do?','打算 introduces an intention, not a completed event. The calendar expression sets the day for the whole exchange.'),
 line('Mei','我|想|跟|你|坐|火車|出去|玩|。|早上|去|，|怎麼樣|？','Wǒ xiǎng gēn nǐ zuò huǒchē chūqù wán. Zǎoshang qù, zěnmeyàng?','I’d like to take a train trip with you. How about going in the morning?','跟 introduces a companion and 坐 names the transport. 怎麼樣 invites a reaction, so this first plan remains open to change.'),
 line('Lin','早上|不行|，|我|要|做|功課|。|大概|中午|有空|。','Zǎoshang bùxíng, wǒ yào zuò gōngkè. Dàgài zhōngwǔ yǒukòng.','Morning won’t work; I need to do homework. I’ll probably be free around noon.','不行 rejects feasibility rather than granting or refusing permission. 大概 makes the free time approximate, not an exact appointment.'),
 line('Mei','那|我們|下午|去|附近|的|地方|吧|。','Nà wǒmen xiàwǔ qù fùjìn de dìfang ba.','Then let’s go somewhere nearby in the afternoon.','那 connects a response to the obstacle just mentioned. The new proposal changes both timing and the kind of outing.'),
 line('Lin','學校|附近|有|一|家|有名|的|餐廳|，|我們|去|吃飯|吧|。','Xuéxiào fùjìn yǒu yì jiā yǒumíng de cāntīng, wǒmen qù chīfàn ba.','There’s a famous restaurant near school. Let’s eat there.','A place-first 有 sentence introduces the restaurant. The following suggestion makes the nearby destination concrete.'),
 line('Mei','坐|捷運|還是|坐|公車|？|捷運|比|公車|快|。','Zuò jiéyùn háishì zuò gōngchē? Jiéyùn bǐ gōngchē kuài.','Metro or bus? The metro is faster than the bus.','還是 asks the choice; 比 supplies one reason to favor the metro. Faster does not imply cheaper, which the passage never compares.'),
 line('Lin','好|，|我們|坐|捷運|。|下午|兩|點|在|學校|外面|見面|。','Hǎo, wǒmen zuò jiéyùn. Xiàwǔ liǎng diǎn zài xuéxiào wàimiàn jiànmiàn.','Okay, let’s take the metro. Meet outside the school at two in the afternoon.','The acceptance selects the metro and gives a precise time and meeting place, replacing the earlier approximate noon availability.'),
 line('Mei','沒問題|！|晚上|我|想|在|家|看|電視|。','Méi wèntí! Wǎnshang wǒ xiǎng zài jiā kàn diànshì.','No problem! In the evening I want to watch television at home.','沒問題 confirms the meeting. The separate evening intention belongs to Mei and does not say Lin will watch television too.')
 ],[
 q('Which plan do they finally agree on?',['A morning train journey','Homework together all afternoon','A bus ride at noon','An afternoon restaurant outing by metro'],3,[4,5,6,7],'The restaurant replaces the train-trip idea; they choose the metro and confirm the afternoon meeting.'),
 q('Why is the morning idea dropped?',['The restaurant is closed','Lin needs to do homework','Mei dislikes trains','The metro is slow'],1,[2],'Lin explicitly says morning is not feasible because of homework. No transport failure is mentioned.'),
 q('When and where is their confirmed meeting?',['Two p.m. outside the school','Noon inside the restaurant','Two p.m. at Mei’s home','Morning at the train station'],0,[6,7],'Lin proposes a specific two o’clock meeting outside the school, and Mei accepts in the next message.'),
 q('What is said only about Mei’s evening?',['She will do Lin’s homework','She will take a train','She wants to watch television at home','She will eat with the whole class'],2,[7],'The evening sentence has Mei as its speaker and subject. It does not extend that plan to both people.')
 ],['Track revisions: the first proposed transport and time may not survive to the accepted plan.','Approximate availability and a confirmed meeting time serve different purposes.']),
 reading(29,'Two dates, one visiting friend','schedule','Read a short visit itinerary and its conditions. A date tells you when; the notes tell you whether the plan is definite.',
 ['u29-calendar-date','u29-yaoshi-jiu','u27-duration-basic','u27-de-shihou'],[
 line('5/6 · arrival','我|的|朋友|五|月|六|號|來|，|要|在|這裡|玩|三|天|。','Wǒ de péngyǒu wǔ yuè liù hào lái, yào zài zhèlǐ wán sān tiān.','My friend comes on May sixth and will spend three days here visiting.','五月六號 is a date before the action. 三天 follows 玩 to give the duration of the visit rather than another calendar date.'),
 line('5/6 · afternoon','下午|我們|打算|到|學校|附近|吃飯|。','Xiàwǔ wǒmen dǎsuàn dào xuéxiào fùjìn chīfàn.','In the afternoon we plan to eat near the school.','打算 labels an intention and 到 introduces the destination. The date is inherited from this part of the itinerary.'),
 line('5/6 · evening','晚上|要是|他|有空|，|我們|就|去|逛|夜市|。','Wǎnshang yàoshi tā yǒukòng, wǒmen jiù qù guàng yèshì.','If he is free in the evening, we’ll visit the night market.','要是 states a condition and 就 its consequence. The evening outing is not guaranteed merely because it appears on the itinerary.'),
 line('5/7 · morning','七|號|早上|我|有|中文|課|，|他|自己|去|買|水果|。','Qī hào zǎoshang wǒ yǒu Zhōngwén kè, tā zìjǐ qù mǎi shuǐguǒ.','On the morning of the seventh I have Chinese class; he will buy fruit by himself.','The month is understood from the previous date. 自己 makes clear the friend’s errand is separate from the narrator’s class.'),
 line('5/7 · afternoon','下午|我們|想|去|貓空|。|聽說|那裡|的|茶館|很|有名|。','Xiàwǔ wǒmen xiǎng qù Māokōng. Tīngshuō nàlǐ de cháguǎn hěn yǒumíng.','In the afternoon we want to go to Maokong. I hear the tea houses there are famous.','聽說 presents reported information that motivates the visit. 那裡 refers to Maokong, not the school mentioned in the previous day’s meal plan.'),
 line('Travel note','要是|坐|公車|去|，|大概|要|一|個|鐘頭|。','Yàoshi zuò gōngchē qù, dàgài yào yí ge zhōngtóu.','If we go by bus, it will probably take one hour.','The condition concerns the travel method. 一個鐘頭 is an estimated duration, and 大概 prevents treating it as an exact guaranteed travel time.'),
 line('Travel note','要是|他|不|想|去|貓空|，|我們|就|在|附近|喝|茶|。','Yàoshi tā bù xiǎng qù Māokōng, wǒmen jiù zài fùjìn hē chá.','If he doesn’t want to go to Maokong, we’ll drink tea nearby.','The condition gives an alternative based on the friend’s preference. It does not say that he has already refused Maokong.'),
 line('Gift note','他|說|要|買|水果|給|我|。|我|喜歡|又|香|又|甜|的|水果|。','Tā shuō yào mǎi shuǐguǒ gěi wǒ. Wǒ xǐhuān yòu xiāng yòu tián de shuǐguǒ.','He says he wants to buy fruit for me. I like fruit that is fragrant and sweet.','給 introduces the recipient of the planned fruit purchase. 又…又… joins two qualities; neither clause names a specific fruit variety.')
 ],[
 q('Which activity depends on the friend being free?',['Buying fruit on the seventh','Attending Chinese class','Visiting the night market on the sixth','Arriving on the sixth'],2,[2],'The night-market line explicitly starts a condition with 要是他有空. It is not an unconditional appointment.'),
 q('Who buys fruit while the narrator is in class?',['The visiting friend, alone','The narrator’s teacher','Both people together','The narrator, alone'],0,[3],'The line contrasts the narrator’s class with 他自己去買水果, assigning the errand to the friend.'),
 q('What happens if the friend does not want to visit Maokong?',['They cancel the entire visit','They take a faster bus','They go to class together','They drink tea nearby'],3,[6],'The alternative clause explicitly pairs not wanting Maokong with drinking tea in the nearby area.'),
 q('Which statement distinguishes the two time expressions correctly?',['May sixth is the length of the stay','May sixth is arrival; three days is the stay length','Three days means arriving on May third','The bus trip lasts three days'],1,[0,5],'The date gives arrival, the duration gives the stay, and the separate bus note gives an estimated hour of travel.')
 ],['Separate unconditional entries from entries introduced by “if.”','A calendar date, a visit duration and an estimated journey length answer different questions.']),
 reading(32,'A room beside the library','notice','A landlord’s short listing and viewing instructions. Match the room’s facilities to the route and meeting details.',
 ['u32-lai-vp','u32-early-jiu','u20-floor','u20-beside','u31-clause-modifier'],[
 line('Listing','圖書館|旁邊|的|大樓|有|一|間|空|房間|，|在|三|樓|。','Túshūguǎn pángbiān de dàlóu yǒu yì jiān kōng fángjiān, zài sān lóu.','The building beside the library has a vacant room on the third floor.','旁邊的大樓 identifies which building; 三樓 identifies the floor. 間 counts rooms, while 空 describes availability.'),
 line('Listing','這|間|是|套房|，|有|浴室|，|沒有|廚房|。','Zhè jiān shì tàofáng, yǒu yùshì, méiyǒu chúfáng.','It is a studio room with a bathroom but no kitchen.','有 and 沒有 distinguish an included facility from a missing one. Do not assume a kitchen just because the room is self-contained.'),
 line('Layout','浴室|在|右邊|，|窗戶|在|左邊|。|房間|很|乾淨|。','Yùshì zài yòubiān, chuānghù zài zuǒbiān. Fángjiān hěn gānjìng.','The bathroom is on the right, the window on the left. The room is clean.','The two sides refer to the room’s described layout. 乾淨 is a separate assessment of condition, not another location.'),
 line('Nearby','樓下|有|超市|，|附近|也|有|餐廳|。','Lóuxià yǒu chāoshì, fùjìn yě yǒu cāntīng.','There is a supermarket downstairs and there are also restaurants nearby.','樓下 and 附近 are different location scopes. The restaurants are nearby; the text does not place all of them downstairs.'),
 line('Travel','從|這裡|到|學校|，|走路|五|分鐘|就|到|了|。','Cóng zhèlǐ dào xuéxiào, zǒulù wǔ fēnzhōng jiù dào le.','From here to school, it is only a five-minute walk.','從…到… sets a route. 就 presents arrival as quick or easy; the five-minute figure belongs to walking, not to a bus journey.'),
 line('Viewing','你|可以|星期|六|下午|來|看|房間|。','Nǐ kěyǐ xīngqíliù xiàwǔ lái kàn fángjiān.','You can come see the room on Saturday afternoon.','來看房間 states the purpose of coming. This is an invitation to view, not evidence that a rental agreement already exists.'),
 line('Viewing','星期|六|下午|我|在|樓下|。|你|可以|來|找|我|。','Xīngqíliù xiàwǔ wǒ zài lóuxià. Nǐ kěyǐ lái zhǎo wǒ.','I’ll be downstairs on Saturday afternoon. You can come find me.','The landlord states a location for the viewing time. 來找我 invites the visitor to meet there, distinct from the room’s third-floor location.'),
 line('Visitor','我|喜歡|自己|做飯|。|這|間|沒有|廚房|，|我|想|再|看|看|。','Wǒ xǐhuān zìjǐ zuòfàn. Zhè jiān méiyǒu chúfáng, wǒ xiǎng zài kànkan.','I like cooking for myself. This room has no kitchen; I’d like to look some more.','The visitor relates the missing facility to a personal preference. 再看看 leaves the decision open rather than confirming a rental.')
 ],[
 q('Which facility is in the room?',['A kitchen','A bathroom','A supermarket','A restaurant'],1,[1,3],'The room includes a bathroom and explicitly lacks a kitchen. The supermarket and restaurants are separate nearby facilities.'),
 q('Where can the visitor find the landlord?',['At school','At the window','Inside the library','Downstairs'],3,[6],'The landlord says they will be downstairs and invites the visitor to come there, even though the vacant room is on the third floor.'),
 q('What is the visitor’s main reservation?',['There is no kitchen for cooking','The room is dirty','The bathroom is missing','The school is an hour away'],0,[1,7],'The visitor likes cooking and explicitly connects hesitation to the missing kitchen.'),
 q('What does the five-minute estimate describe?',['A phone call','Viewing the bathroom','Walking from the building to school','A metro ride'],2,[4],'The route names the building and school, and 走路 identifies the method as walking.')
 ],['Do not merge the room’s facilities with amenities elsewhere in the building or neighborhood.','A viewing arrangement is not a decision to rent.'],{'分鐘':{pinyin:'fēnzhōng',meaning:'minute (duration)',note:'Reading support for the duration expression already used in the Unit 32 walking example; not a new practice target.',unfamiliar:true}}),
 reading(35,'Who pays, and what comes next?','messages','Two friends discuss a study plan in a LINE-style chat. Keep past payment, current study and future hopes separate.',
 ['u35-shi-de','u34-first-then','u31-yinwei-suoyi'],[
 line('Lin','你|在|臺灣|打算|念|多久|的|書|？','Nǐ zài Táiwān dǎsuàn niàn duōjiǔ de shū?','How long are you planning to study in Taiwan?','多久 asks for duration, not a calendar date. 念多久的書 is the taught pattern that places the study duration inside the phrase.'),
 line('Mei','我|計畫|先|在|語言中心|念|一|年|中文|，|再|念|大學|。','Wǒ jìhuà xiān zài yǔyán zhōngxīn niàn yì nián Zhōngwén, zài niàn dàxué.','I plan to study Chinese at the language center for a year first, then attend university.','先…再… gives the sequence. The stated year belongs to Chinese study; it does not give the total length of university study.'),
 line('Lin','學費|是|你|自己|付|的|嗎|？','Xuéfèi shì nǐ zìjǐ fù de ma?','Was it you who paid the tuition yourself?','是…的 focuses on who paid a known expense. The question seeks a detail of the payment rather than asking what the tuition costs.'),
 line('Mei','不|是|我|自己|付|的|，|是|公司|替|我|付|的|。','Bú shì wǒ zìjǐ fù de, shì gōngsī tì wǒ fù de.','I didn’t pay it myself; the company paid it for me.','The correction replaces the assumed payer. 替我 means on my behalf, making the company the payer and Mei the beneficiary.'),
 line('Lin','你|也|有|獎學金|嗎|？','Nǐ yě yǒu jiǎngxuéjīn ma?','Do you also have a scholarship?','也 asks about a possible additional source of support. This question does not establish that a scholarship actually exists.'),
 line('Mei','沒有|。|我|希望|以後|在|這|家|公司|上班|。','Méiyǒu. Wǒ xīwàng yǐhòu zài zhè jiā gōngsī shàngbān.','No. I hope to work at this company in the future.','沒有 answers the scholarship question. 希望 marks a hope, so future employment must not be treated as a current job or guaranteed offer.'),
 line('Lin','你|每天|念書|，|累|不|累|？','Nǐ měitiān niànshū, lèi bú lèi?','You study every day. Is it tiring?','每天 describes frequency and 累不累 asks about the resulting feeling. This line adds no new source of money or work arrangement.'),
 line('Mei','有一點|累|，|可是|我|喜歡|學|中文|。|我|希望|成績|好|。','Yǒuyìdiǎn lèi, kěshì wǒ xǐhuān xué Zhōngwén. Wǒ xīwàng chéngjī hǎo.','A little tiring, but I like learning Chinese. I hope to get good grades.','有一點 gives a mild negative assessment. 可是 contrasts that difficulty with enjoyment; the grades remain a hoped-for result.')
 ],[
 q('What is the planned study order?',['University, then Chinese','Work, then a scholarship','Chinese for a year, then university','A year at university, then stop'],2,[1],'先 identifies Chinese study as the first stage and 再 introduces university afterward.'),
 q('Who paid the tuition?',['The company, on Mei’s behalf','Lin’s family','Mei personally','The language teacher'],0,[2,3],'Mei explicitly corrects the assumption that she paid it herself and names the company as payer.'),
 q('Which statement is a hope rather than an established fact?',['Mei has no scholarship','The company paid tuition','Mei enjoys Chinese','Mei will work at that company'],3,[3,5,7],'Mei uses 希望 for future employment. Payment by the company does not by itself establish a job offer.'),
 q('How does Mei describe studying?',['Easy and boring','A little tiring but enjoyable','Impossible without a scholarship','Something she no longer does'],1,[7],'Mei combines slight tiredness with liking Chinese, rather than choosing only a positive or negative description.')
 ],['Separate who performed an action from who benefited from it.','Hope, intention and fact are different levels of commitment.']),
 reading(38,'After class means after class','dialogue','Two friends arrange a birthday visit around a language exchange. Find the actual meeting trigger and place.',
 ['u38-yi-jiu','u21-clock-time','u34-first-then'],[
 line('Lin','好久不見|！|明天|是|你|的|生日|，|對|不|對|？','Hǎojiǔ bú jiàn! Míngtiān shì nǐ de shēngrì, duì bú duì?','Long time no see! Tomorrow is your birthday, right?','The greeting establishes a reunion. 對不對 asks for confirmation of the birthday date, rather than introducing a choice between two dates.'),
 line('Mei','對|，|你|還|記得|！|我|明天|下午|有|語言|交換|。','Duì, nǐ hái jìde! Wǒ míngtiān xiàwǔ yǒu yǔyán jiāohuàn.','Yes, you still remember! I have a language exchange tomorrow afternoon.','還記得 expresses continued memory. The afternoon exchange is a separate commitment that the birthday visit must fit around.'),
 line('Lin','跟|誰|？|是|那|個|很|熱心|的|朋友|嗎|？','Gēn shéi? Shì nà ge hěn rèxīn de péngyǒu ma?','With whom? Is it that very helpful friend?','跟誰 asks for the companion. 很熱心的 identifies a person by a known quality, not by a new name the learner must decode.'),
 line('Mei','對|。|他|教|我|西班牙文|，|我|教|他|中文|。','Duì. Tā jiāo wǒ Xībānyáwén, wǒ jiāo tā Zhōngwén.','Yes. He teaches me Spanish, and I teach him Chinese.','Each clause reverses teacher and learner. Follow the subject before 教 to avoid swapping who teaches which language.'),
 line('Lin','那|我們|什麼|時候|見面|？|我|四|點|左右|有空|。','Nà wǒmen shénme shíhòu jiànmiàn? Wǒ sì diǎn zuǒyòu yǒukòng.','Then when shall we meet? I’m free around four.','左右 makes four o’clock approximate. This describes Lin’s availability, not yet the exact time of their joint meeting.'),
 line('Mei','我|三|點|半|有|課|，|四|點|半|下課|。|我|一|下課|就|去|找|你|。','Wǒ sān diǎn bàn yǒu kè, sì diǎn bàn xiàkè. Wǒ yí xiàkè jiù qù zhǎo nǐ.','I have class at three thirty and finish at four thirty. I’ll come find you as soon as class ends.','一…就… links the visit immediately to the end of class. It overrides any assumption that being free around four guarantees a four o’clock meeting.'),
 line('Lin','好|，|我|在|圖書館|門口|等|你|。|我們|先|喝|茶|，|再|吃飯|。','Hǎo, wǒ zài túshūguǎn ménkǒu děng nǐ. Wǒmen xiān hē chá, zài chīfàn.','Okay, I’ll wait at the library entrance. We’ll have tea first and then eat.','門口 fixes the meeting point at the entrance, not inside. 先…再… orders two shared activities after they meet.'),
 line('Mei','太好了|！|我|也|很|想|和|你|一起|吃飯|。','Tài hǎo le! Wǒ yě hěn xiǎng hé nǐ yìqǐ chīfàn.','Great! I’m really looking forward to eating with you too.','The enthusiastic response accepts the arrangement and expresses a shared wish. It does not move the meeting to an earlier time.')
 ],[
 q('What triggers Mei’s visit?',['The start of her class','Finishing class at four thirty','Lin becoming free at four','The start of the language exchange'],1,[4,5],'Mei says she will go as soon as class ends, and explicitly places that end at four thirty.'),
 q('Who teaches Spanish in the exchange?',['Lin teaches Mei','Mei teaches the friend','Mei teaches Lin','The helpful friend teaches Mei'],3,[2,3],'The friend is the subject of 他教我西班牙文, while Mei teaches Chinese in return.'),
 q('Where and in what activity order will they meet?',['Library entrance; tea then food','Inside class; food then tea','Dormitory; Spanish then Chinese','Library entrance; food then tea'],0,[6],'The agreed entrance and the 先…再… sequence together identify the correct arrangement.'),
 q('Why is “exactly four o’clock” not a good summary?',['The library closes at four','They meet in the morning','Lin gives an approximate time and Mei finishes later','Mei cancels the visit'],2,[4,5],'左右 makes Lin’s time approximate, while Mei’s class ends at four thirty and the visit follows that event.')
 ],['An event trigger can determine a plan more precisely than someone’s approximate availability.','In reciprocal exchanges, re-check the subject of each clause rather than assuming one person is always the teacher.']),
 reading(41,'Birthday dinner: ordered or only suggested?','messages','Read a birthday group chat. Distinguish what is already ordered, what someone will bring, and what is only proposed.',
 ['u39-verbal-le','u39-bu-vs-mei','u41-shibushi','u41-gen-yiyang','u40-questionword-totality'],[
 line('Lin','明天|是|Mei|的|生日|。|我|訂|了|豬腳|麵線|，|也|訂|了|蛋糕|。','Míngtiān shì Mei de shēngrì. Wǒ dìng le zhūjiǎo miànxiàn, yě dìng le dàngāo.','Tomorrow is Mei’s birthday. I’ve ordered pork-knuckle noodles and a cake.','了 after 訂 marks completed ordering. The food may be eaten tomorrow even though the order has already been placed.'),
 line('Chen','你|是|不|是|也|訂|了|牛肉|麵|？','Nǐ shì bú shì yě dìng le niúròu miàn?','Did you also order beef noodles?','是不是 requests confirmation of a possible additional order. The question itself is not evidence that beef noodles are included.'),
 line('Lin','沒有|，|我|沒|訂|牛肉|麵|。|Mei|什麼|都|吃|，|可是|她|最|喜歡|麵線|。','Méiyǒu, wǒ méi dìng niúròu miàn. Mei shénme dōu chī, kěshì tā zuì xǐhuān miànxiàn.','No, I didn’t order beef noodles. Mei eats everything, but her favorite is thin noodles.','沒 negates a completed action without retaining verbal 了. 什麼都 expresses an inclusive range, while 最 still allows a favorite within it.'),
 line('Chen','我|買|了|一|本|書|，|明天|給|她|。','Wǒ mǎi le yì běn shū, míngtiān gěi tā.','I bought a book; I’ll give it to her tomorrow.','The purchase is completed, but the giving is scheduled for tomorrow. Keep the two actions and their times separate.'),
 line('Mei','謝謝|你們|！|你們|跟|我|的|家人|一樣|，|都|很|熱心|。','Xièxie nǐmen! Nǐmen gēn wǒ de jiārén yíyàng, dōu hěn rèxīn.','Thank you! You’re like my family—both so helpful.','跟…一樣 compares the friends with Mei’s family, and 都很熱心 specifies the shared quality. It does not claim the friends are relatives.'),
 line('Lin','不必客氣|。|明天|晚上|六|點|在|我|家|吃飯|。','Bú bì kèqì. Míngtiān wǎnshang liù diǎn zài wǒ jiā chīfàn.','You’re welcome. Dinner is at my home at six tomorrow evening.','Time precedes location and the meal action. The speaker’s 我家 identifies Lin’s home rather than Mei’s or Chen’s.'),
 line('Chen','吃飯|以後|，|我們|唱歌|，|好不好|？','Chīfàn yǐhòu, wǒmen chànggē, hǎo bù hǎo?','Shall we sing after dinner?','以後 places the proposed activity after eating. 好不好 seeks agreement; no following message explicitly accepts the singing plan.'),
 line('Lin','Mei|，|祝|你|生日快樂|，|心想事成|！','Mei, zhù nǐ shēngrì kuàilè, xīn xiǎng shì chéng!','Mei, happy birthday! May your wishes come true!','祝 introduces wishes directed to the recipient. A birthday wish closes the chat warmly but does not answer every earlier planning question.')
 ],[
 q('Which items has Lin already ordered?',['Beef noodles and a book','Only a cake','Pork-knuckle noodles and a cake','A book and thin noodles'],2,[0,1,2],'Lin explicitly names the two completed orders and denies ordering beef noodles.'),
 q('Which part of Chen’s gift plan is already completed?',['Buying the book','Giving Mei the book','Reading it together','Wrapping the cake'],0,[3],'買了 marks the purchase as completed; 明天 places giving the book in the future.'),
 q('At whose home is dinner?',['Mei’s','Chen’s','A family member’s, not identified','Lin’s'],3,[5],'Lin is the speaker who says 我家, so the home belongs to Lin in the conversation.'),
 q('Which activity remains a proposal without an explicit acceptance?',['Dinner at six','Singing after dinner','Buying the gift book','Ordering the cake'],1,[6,7],'Chen proposes singing with 好不好. The final birthday wish does not explicitly confirm that proposal.')
 ],['An action can be completed before a future celebration: ordering today and eating tomorrow are compatible.','Resolve “my home” from the speaker label, and distinguish warm replies from explicit acceptance of a plan.']),
 reading(44,'The weather update changes the outing','notice','Read a weather note and the conversation it prompts. Compare today with yesterday, then identify the group’s final plan.',
 ['u44-even-more','u44-not-as','u43-imminent','u29-yaoshi-jiu'],[
 line('Weather note','今天|有|颱風|。|風|比|昨天|更|大|，|雨|也|很|大|。','Jīntiān yǒu táifēng. Fēng bǐ zuótiān gèng dà, yǔ yě hěn dà.','There is a typhoon today. The wind is even stronger than yesterday, and the rain is heavy too.','比 sets yesterday as the comparison baseline. 更 emphasizes a further increase; the rain is described as heavy without an explicit yesterday comparison.'),
 line('Weather note','今天|沒有|昨天|那麼|冷|，|可是|外面|很|濕|。','Jīntiān méiyǒu zuótiān nàme lěng, kěshì wàimiàn hěn shī.','Today is not as cold as yesterday, but it is very wet outside.','沒有…那麼… expresses a lower degree of cold. Milder temperature does not mean weaker wind or better conditions overall.'),
 line('Lin · message','我們|今天|還|去|山上|看|風景|嗎|？','Wǒmen jīntiān hái qù shānshàng kàn fēngjǐng ma?','Are we still going up the mountain to see the scenery today?','還 asks whether a previous plan remains in effect. Asking about the trip is not the same as confirming that it will happen.'),
 line('Mei · reply','不|去|了|。|我|覺得|這次|颱風|比|上次|更|可怕|。','Bú qù le. Wǒ juéde zhè cì táifēng bǐ shàng cì gèng kěpà.','We’re not going now. I think this typhoon is even scarier than the last one.','Sentence-final 了 signals a changed plan. 我覺得 frames the comparison as Mei’s assessment, not a numerical weather measurement.'),
 line('Lin · message','那|我們|在|家|看|電影|吧|。|我|有|一|部|很|好看|的|電影|。','Nà wǒmen zài jiā kàn diànyǐng ba. Wǒ yǒu yí bù hěn hǎokàn de diànyǐng.','Then let’s watch a movie at home. I have a very good movie.','那 connects an alternative to the cancellation. 在家 changes the location of the activity, rather than finding another outdoor destination.'),
 line('Mei · reply','好啊|。|我|先|看|新聞|，|再|跟|你|看|電影|。','Hǎo a. Wǒ xiān kàn xīnwén, zài gēn nǐ kàn diànyǐng.','Sure. I’ll watch the news first, then watch the movie with you.','好啊 accepts the indoor activity. 先…再… adds an order to the activities without reversing the cancellation of the mountain trip.'),
 line('Lin · message','雨|要|停|了|嗎|？','Yǔ yào tíng le ma?','Is the rain about to stop?','要…了 asks about an imminent change. Because this is a question, it does not establish that the rain is actually stopping.'),
 line('Mei · reply','我|不|知道|。|要是|你|出去|，|一定|要|小心|。','Wǒ bù zhīdào. Yàoshi nǐ chūqù, yídìng yào xiǎoxīn.','I don’t know. If you go out, be sure to be careful.','The reply leaves the weather change unknown. 要是 introduces a conditional warning, not a new agreement to go outdoors together.')
 ],[
 q('Compared with yesterday, what is stated about today?',['Colder with weaker wind','Less cold but stronger wind','Less wet with weaker wind','Colder and dry'],1,[0,1],'The wind comparison says stronger, while the temperature comparison says not as cold. These are different dimensions.'),
 q('What is the agreed replacement activity?',['A shorter mountain trip','Visiting a friend outdoors','Going to the library','Watching a movie at home after the news'],3,[3,4,5],'Mei cancels the trip and accepts the movie plan, adding that she will watch the news first.'),
 q('Do they know the rain is about to stop?',['No; the question receives “I don’t know”','Yes; Lin confirms it','Yes; warmer weather proves it','No; they know it will never stop'],0,[6,7],'The question is explicitly answered with uncertainty. It cannot be used as evidence for an imminent weather change.'),
 q('Which statement is specifically Mei’s personal comparison?',['Today’s rain is heavy','Today is less cold','This typhoon feels scarier than the last','The movie is already over'],2,[3],'我覺得 marks Mei’s assessment of this typhoon compared with the previous one.')
 ],['Compare one property at a time: less cold can coexist with stronger wind.','Do not turn a question about what might happen into a forecast that it will happen.'],{'部':{pinyin:'bù',meaning:'measure word for films',note:'Reading-only support for counting one film.',unfamiliar:true},'電影':{pinyin:'diànyǐng',meaning:'movie; film',note:'The movie noun from the already-taught expression 看電影, to watch a movie.'}}),
 reading(47,'A friend offers to come along','dialogue','Read a conversation about feeling ill. This is language practice: follow the reported symptoms and the offer of help, not medical advice.',
 ['u47-vle-jiu','u46-noncommittal-question-words','u39-bu-vs-mei'],[
 line('Mei','你|怎麼了|？|臉色|不|太|好看|。','Nǐ zěnme le? Liǎnsè bú tài hǎokàn.','What’s wrong? You don’t look very well.','怎麼了 asks about a problem or changed situation. The observation concerns appearance and does not by itself establish a diagnosis.'),
 line('Lin','我|昨天|晚上|肚子|痛|，|吐|了|兩|次|。','Wǒ zuótiān wǎnshang dùzi tòng, tù le liǎng cì.','My stomach hurt last night, and I vomited twice.','昨天晚上 supplies the time. 次 counts occurrences of vomiting, not the number of days the person has been ill.'),
 line('Mei','今天|還|痛|嗎|？|你|有|沒有|發燒|？','Jīntiān hái tòng ma? Nǐ yǒu méiyǒu fāshāo?','Does it still hurt today? Do you have a fever?','還 asks whether the earlier symptom continues. The second question asks about another symptom without asserting that it is present.'),
 line('Lin','今天|還|有一點|痛|，|沒有|發燒|。|我|沒|吃|什麼|東西|。','Jīntiān hái yǒuyìdiǎn tòng, méiyǒu fāshāo. Wǒ méi chī shénme dōngxi.','It still hurts a little today, but I don’t have a fever. I haven’t eaten much.','In a negative statement, 沒吃什麼東西 means not eating much or anything substantial; 什麼 is not asking the reader to name a food.'),
 line('Mei','你|去|看|醫生|了|嗎|？','Nǐ qù kàn yīshēng le ma?','Have you been to see a doctor?','The question checks whether a visit has happened. It must be read together with the reply rather than assumed to confirm an earlier visit.'),
 line('Lin','還|沒有|。|我|有|健康|保險|，|等一下|就|去|健康中心|。','Hái méiyǒu. Wǒ yǒu jiànkāng bǎoxiǎn, děng yíxià jiù qù jiànkāng zhōngxīn.','Not yet. I have health insurance, and I’ll go to the health center shortly.','還沒有 denies a completed visit. 等一下就 presents going to the health center as a near-future plan, not something that has already happened.'),
 line('Mei','我|陪|你|去|。|你|看|了|醫生|就|跟|我|去|拿|藥|，|好不好|？','Wǒ péi nǐ qù. Nǐ kàn le yīshēng jiù gēn wǒ qù ná yào, hǎo bù hǎo?','I’ll go with you. After you’ve seen the doctor, shall we go get medicine together?','V了…就… sequences a proposed next action after the first is completed. Here 了 does not mean the doctor visit has already happened.'),
 line('Lin','謝謝|。|我|的|朋友|等一下|來|，|他|陪|我|去|。|你|不|用|陪|我|。','Xièxie. Wǒ de péngyǒu děng yíxià lái, tā péi wǒ qù. Nǐ bú yòng péi wǒ.','Thanks. My friend is coming shortly and will go with me. You don’t need to come along.','Lin gives a reason for declining Mei’s offer: another friend will accompany him. The refusal concerns the companion, not whether to seek help.')
 ],[
 q('What happened twice?',['Lin visited the clinic','Lin took medicine','Lin vomited last night','Mei called a doctor'],2,[1],'兩次 counts the vomiting episodes. No completed doctor visits or medicine doses are counted in the passage.'),
 q('Which description matches Lin today?',['Some stomach pain, no fever, little food','Fever but no stomach pain','No symptoms and a large lunch','Only a sore throat'],0,[2,3],'Lin’s reply says there is still some pain, denies fever and states that he has eaten little.'),
 q('Has Lin already seen a doctor?',['Yes, twice','Yes, just before the chat','The passage says he never will','No; he says “not yet” and plans to go'],3,[4,5],'還沒有 directly answers the visit question. The proposed sequence in the next line is not proof of a completed visit.'),
 q('Why does Lin decline Mei’s company?',['He decides not to go','Another friend is coming to accompany him','He is already at the pharmacy','He has no insurance'],1,[7],'Lin says another friend will accompany him, so Mei’s help is unnecessary. He does not cancel the health-center plan.')
 ],['Separate a symptom report from a question and from a diagnosis the passage never provides.','In a future sequence, V了…就… can describe what will happen after completing an action, not what has already happened.']),
];
