// Short original readings fill the units between existing checkpoints.
const line=(speaker,text,pinyin,translation,note)=>({speaker,text,pinyin,translation,note});
const q=(prompt,options,answer,evidence,explanation)=>({prompt,options,answer,evidence,explanation});
const mini=(unit,title,presentation,setup,grammarIds,lines,questions,tips)=>({unit,title,presentation,setup,grammarIds,lines,questions,tips,glosses:{},short:true});
export const miniSpecs=[
 mini(12,'One order, two prices','notice','Read a small drink-order card. Use both the quantities and the prices.', ['u12-price','u12-total','u11-takeout'],[
 line('Price card','熱|茶|一|杯|二|十|塊|，|熱|咖啡|一|杯|四|十|塊|。','Rè chá yì bēi èrshí kuài, rè kāfēi yì bēi sìshí kuài.','Hot tea is twenty dollars a cup; hot coffee is forty dollars a cup.','Each 一杯 gives the price for one cup. The two prices belong to different drinks, not to two sizes of the same drink.'),
 line('Order','我|要|兩|杯|熱|茶|，|一|杯|熱|咖啡|。','Wǒ yào liǎng bēi rè chá, yì bēi rè kāfēi.','I’d like two hot teas and one hot coffee.','兩杯 counts the teas, while 一杯 counts the coffee. Keep those quantities with the correct prices on the card.'),
 line('Customer','都|外帶|。|一共|多少|錢|？','Dōu wàidài. Yígòng duōshǎo qián?','All to go. How much altogether?','都 covers all three cups from the order. 一共 asks for the total, not the price of just the final cup.'),
 line('Staff','一共|八|十|塊|。|謝謝|！','Yígòng bāshí kuài. Xièxie!','Eighty dollars altogether. Thank you!','Two teas cost forty, and one coffee costs another forty. The total therefore agrees with the prices and quantities above.')
 ],[
 q('Which calculation matches the order?',['20 + 40 = 60','20 + 20 + 40 = 80','40 + 40 + 20 = 100','20 + 20 = 40'],1,[0,1,3],'There are two twenty-dollar teas and one forty-dollar coffee, giving the stated eighty-dollar total.'),
 q('Which drinks are to go?',['Only the coffee','Only the teas','One tea and the coffee','All three drinks'],3,[1,2],'都 applies to the entire preceding order: the two teas and the coffee are all takeout.')
 ],['Match each quantity to its item before calculating.','Scope words such as 都 can apply to several items named earlier.']),
 mini(15,'The noodle-shop order slip','notice','Read an order slip and the customer’s comment. Distinguish quantities from opinions.', ['u15-order','u15-favorite','u15-soup'],[
 line('Order','牛肉|麵|兩|碗|，|湯|一|碗|。','Niúròu miàn liǎng wǎn, tāng yì wǎn.','Two bowls of beef noodles and one bowl of soup.','Order slips can put the item before its quantity. 碗 counts bowls for both items, but their quantities are different.'),
 line('Service','內用|，|不|外帶|。','Nèiyòng, bú wàidài.','For here, not to go.','The service line applies to the whole order. It does not change the food or the number of bowls listed above.'),
 line('Customer','我|最|喜歡|這|家|店|的|牛肉|麵|，|真|好吃|！','Wǒ zuì xǐhuān zhè jiā diàn de niúròu miàn, zhēn hǎochī!','This shop’s beef noodles are my favorite. They’re really delicious!','最 identifies the customer’s strongest preference. 真好吃 is an opinion about taste, not a statement about price.'),
 line('Companion','我|也|喜歡|牛肉|麵|。|今天|我|想|喝|湯|。','Wǒ yě xǐhuān niúròu miàn. Jīntiān wǒ xiǎng hē tāng.','I like beef noodles too. Today I feel like soup.','The companion separates a general preference from today’s choice. This contrast does not remove the noodles already on the slip.')
 ],[
 q('How many bowls are listed altogether?',['Three','Two','One','Four'],0,[0],'The slip lists two bowls of noodles plus one bowl of soup, so the total is three bowls.'),
 q('What does the customer’s comment establish?',['The noodles are cheapest','The soup is free','The noodles are the customer’s favorite','Everything is takeout'],2,[1,2],'最喜歡 identifies a favorite. The comment gives no price comparison, and the service line says for here.')
 ],['A slip often omits full sentence wording; item and quantity still stay paired.','A favorite food is a preference, not evidence about its price.']),
 mini(18,'Where is everyone now?','messages','Read a short exchange during class time. Follow the correction and the two different people.', ['u18-now','u18-not-at','u18-library','u18-location-action'],[
 line('Lin','你|現在|在|學校|外面|嗎|？','Nǐ xiànzài zài xuéxiào wàimiàn ma?','Are you outside the school now?','現在 asks about current whereabouts. Because the location appears in a question, it is not yet an established fact.'),
 line('Mei','不|，|我|在|圖書館|裡面|看|書|。','Bù, wǒ zài túshūguǎn lǐmiàn kàn shū.','No, I’m reading inside the library.','不 rejects the suggested location. 在圖書館裡面 comes before 看書 to place the reading activity inside the library.'),
 line('Lin','你|姐姐|也|在|那裡|嗎|？','Nǐ jiějie yě zài nàlǐ ma?','Is your older sister there too?','那裡 points back to the library. 也 asks whether the sister shares Mei’s location, rather than asserting that she does.'),
 line('Mei','她|不|在|圖書館|，|她|在|學校|上課|。','Tā bú zài túshūguǎn, tā zài xuéxiào shàngkè.','She isn’t in the library; she’s having class at school.','不在 denies one location, and the second clause gives the sister’s activity. Mei and her sister are doing different things.')
 ],[
 q('Who is reading in the library?',['Lin','Mei','Mei’s sister','Everyone'],1,[1,3],'Mei says she is reading there, while her sister is specifically said not to be in the library.'),
 q('What does “there” in Lin’s second message refer to?',['Outside the school','A restaurant','Mei’s home','Inside the library'],3,[1,2],'The immediately preceding answer establishes the library as the location that 那裡 refers back to.')
 ],['Do not treat a location question as a fact.','Resolve “there” from the last established location.']),
 mini(21,'The free hour is not the whole afternoon','schedule','Read a short availability note and a reply. Find a meeting time inside the stated window.', ['u21-clock-time','u21-from-to-time','u21-time-before-place'],[
 line('Mei · availability','明天|從|中午|十|二|點|到|一|點|，|我|有空|。','Míngtiān cóng zhōngwǔ shí’èr diǎn dào yì diǎn, wǒ yǒukòng.','Tomorrow I’m free from noon until one.','從…到… gives both boundaries of availability. It does not say that Mei is free throughout the rest of the day.'),
 line('Mei · location','我|在|學校|附近|。|我們|在|圖書館|外面|見面|吧|。','Wǒ zài xuéxiào fùjìn. Wǒmen zài túshūguǎn wàimiàn jiànmiàn ba.','I’ll be near school. Let’s meet outside the library.','The first clause gives a broad area; the second proposes a more precise meeting point outside, rather than inside, the library.'),
 line('Lin · proposal','十|二|點|二|十|分|見面|，|好不好|？','Shí’èr diǎn èrshí fēn jiànmiàn, hǎo bù hǎo?','Shall we meet at twelve twenty?','The hour comes before 點 and the minutes before 分. This time falls within Mei’s stated noon-to-one window.'),
 line('Mei · reply','沒問題|。|一|點|我|要|去|上課|。','Méi wèntí. Yì diǎn wǒ yào qù shàngkè.','No problem. At one I need to go to class.','The reply accepts the proposed time and explains the end of the free window. Going to class limits how long the meeting can continue.')
 ],[
 q('Which appointment is accepted?',['12:20 outside the library','1:20 inside the library','12:00 inside the classroom','1:00 at home'],0,[1,2,3],'The place comes from Mei’s proposal, the time from Lin’s reply, and 沒問題 confirms their combination.'),
 q('Why should they not assume Mei is free after one?',['The library closes','Lin goes home','Mei needs to go to class','Mei has not replied'],2,[0,3],'The window ends at one, and the last message gives class as the reason for that boundary.')
 ],['Combine the time from one message with the place from another.','Check both ends of an availability window.']),
 mini(24,'A faster train, a different choice','dialogue','Two friends compare travel choices. A favorable description does not always tell you what they choose.', ['u24-zuo-transport','u24-gen-company','u24-bijiao','u24-you-you'],[
 line('Lin','明天|你|跟|誰|去|玩|？','Míngtiān nǐ gēn shéi qù wán?','Who are you going out with tomorrow?','跟誰 asks about a companion. The time is tomorrow, so this is a plan rather than a completed trip.'),
 line('Mei','我|跟|姐姐|去|。|我們|想|坐|火車|。','Wǒ gēn jiějie qù. Wǒmen xiǎng zuò huǒchē.','I’m going with my older sister. We want to take the train.','The first sentence answers who, and the second gives their transport preference. 姐姐 is the companion, not the destination.'),
 line('Lin','高鐵|比較|快|，|又|快|又|舒服|。','Gāotiě bǐjiào kuài, yòu kuài yòu shūfu.','High-speed rail is faster; it’s both fast and comfortable.','比較 makes a contextual comparison, and 又…又… joins two favorable qualities. Lin has not yet changed Mei’s stated choice.'),
 line('Mei','我|知道|，|可是|姐姐|覺得|高鐵|車票|太|貴|了|。|我們|坐|火車|吧|。','Wǒ zhīdào, kěshì jiějie juéde gāotiě chēpiào tài guì le. Wǒmen zuò huǒchē ba.','I know, but my sister thinks high-speed rail tickets are too expensive. Let’s take the regular train.','可是 introduces the competing concern: price. The final suggestion keeps the regular train despite the high-speed option’s advantages.')
 ],[
 q('Why does Mei still favor the regular train?',['Her sister cannot travel','The faster option is considered too expensive','The train has already left','Lin says it is fastest'],1,[2,3],'The fast, comfortable option loses out because the sister considers its ticket too expensive.'),
 q('Who is Mei planning to travel with?',['Her teacher','Lin','Her brother','Her older sister'],3,[0,1],'Mei directly answers the companion question with 跟姐姐去. Lin discusses the plan but is not named as her companion.')
 ],['Separate the best-described option from the option actually chosen.','A transport comparison and a companion question ask for different information.']),
 mini(27,'A recommendation is not a decision','messages','Read a brief holiday-planning chat. Notice the difference between someone’s plan and a friend’s advice.', ['u27-duration-basic','u27-yinggai','u27-you-shihou'],[
 line('Mei','放假|的|時候|，|我|打算|去|玩|兩|個|星期|。','Fàngjià de shíhòu, wǒ dǎsuàn qù wán liǎng ge xīngqí.','During the holiday, I plan to go away for two weeks.','的時候 locates the activity during a holiday. 兩個星期 follows the activity to state its duration rather than the date it begins.'),
 line('Lin','你|應該|去|夜市|。|那裡|的|小吃|很|特別|。','Nǐ yīnggāi qù yèshì. Nàlǐ de xiǎochī hěn tèbié.','You should visit the night market. The snacks there are special.','應該 gives advice here. The description explains Lin’s recommendation without proving that Mei has agreed to follow it.'),
 line('Mei','我|有時候|喜歡|去|商店|，|有時候|喜歡|在|茶館|喝|茶|。','Wǒ yǒushíhòu xǐhuān qù shāngdiàn, yǒushíhòu xǐhuān zài cháguǎn hē chá.','Sometimes I like going to shops; sometimes I like having tea at a tea house.','有時候…有時候… describes alternate preferences across occasions. It does not schedule both activities on particular days of this trip.'),
 line('Mei','我|沒有|決定|去|哪裡|。','Wǒ méiyǒu juédìng qù nǎlǐ.','I haven’t decided where to go yet.','The final statement leaves the destination unsettled. It does not cancel the earlier two-week intention or turn the advice into a booking.')
 ],[
 q('Which part of the plan is stated, even though the destination is undecided?',['A two-week outing','A booked night-market visit','A fixed tea-house reservation','A return on Monday'],0,[0,3],'Mei gives a two-week duration but explicitly says the destination has not yet been decided.'),
 q('What role does the night market play?',['A place Mei refuses to visit','A confirmed destination','Lin’s recommendation','The place they are currently in'],2,[1,3],'Lin recommends it with 應該, but Mei’s final message makes clear she has not settled on a destination.')
 ],['A stated duration can coexist with an undecided destination.','Advice is not confirmation that the listener will follow it.']),
 mini(30,'A photo and a guess','notice','Read a photo caption and two comments. Work out which claim the reply confirms.', ['u30-ba-guess','u30-vv-kan','u30-state-redup'],[
 line('Caption','今天|和|朋友|一起|吃|水果|。|芒果|黃|黃|的|，|很|香|。','Jīntiān hé péngyǒu yìqǐ chī shuǐguǒ. Mángguǒ huánghuáng de, hěn xiāng.','Eating fruit with a friend today. The mango is yellow and fragrant.','A caption can omit an understood subject. 黃黃的 presents a descriptive impression of the mango rather than a color comparison.'),
 line('Lin · comment','你|今天|穿|紅色|衣服|吧|？','Nǐ jīntiān chuān hóngsè yīfu ba?','You’re wearing red today, right?','吧 marks a guess offered for confirmation. The guess concerns the person’s clothing today, not the color of the fruit.'),
 line('Mei · reply','對|！|我|很|開心|，|朋友|給|我|照相|。','Duì! Wǒ hěn kāixīn, péngyǒu gěi wǒ zhàoxiàng.','Right! I’m very happy; my friend is taking a photo of me.','對 confirms Lin’s identification. The friend is the photographer, while 我 is the person receiving that help.'),
 line('Mei · reply','這|個|芒果|很|甜|，|你|也|吃吃看|。','Zhè ge mángguǒ hěn tián, nǐ yě chīchīkàn.','This mango is sweet; you should try some too.','吃吃看 invites someone to try the food. The 看 in this pattern adds trying, rather than asking someone merely to look at the mango.')
 ],[
 q('Who is identified as wearing red?',['The photographer','Mei','Lin’s teacher','Nobody; the guess is rejected'],1,[1,2],'Lin guesses that the person in red is Mei, and Mei answers 對 to confirm it.'),
 q('What does Mei invite Lin to do?',['Take another picture','Change clothes','Only look at the mango','Try eating the mango'],3,[3],'吃吃看 means to try eating it. It is not an instruction simply to look at the fruit.')
 ],['Wait for the reply before treating a guess as confirmed.','Read VV看 as a whole try-it pattern.']),
 mini(33,'The rent call has one loose end','messages','Read a tenant–landlord exchange. One payment is confirmed, but a problem remains.', ['u33-existential-you','u33-zero-pronoun'],[
 line('Tenant','喂|，|房東|，|你|收到|房租|了|嗎|？','Wéi, fángdōng, nǐ shōudào fángzū le ma?','Hello, landlord—have you received the rent?','喂 opens a telephone-style exchange. The question checks receipt of the rent, not whether the tenant likes the room.'),
 line('Landlord','收到|了|，|謝謝|。|住|在|這裡|習慣|了|嗎|？','Shōudào le, xièxie. Zhù zài zhèlǐ xíguàn le ma?','Yes, thank you. Have you got used to living here?','收到了 leaves the understood rent unspoken. The following question shifts from payment to becoming accustomed to the home.'),
 line('Tenant','習慣|了|，|不過|熱水器|好像|有|問題|。','Xíguàn le, búguò rèshuǐqì hǎoxiàng yǒu wèntí.','Yes, but there seems to be a problem with the water heater.','不過 introduces a qualification to the positive answer. 好像 makes the problem tentative rather than a precise technical diagnosis.'),
 line('Landlord','不好意思|。|我|明天|來|看|看|。','Bù hǎoyìsi. Wǒ míngtiān lái kànkan.','Sorry about that. I’ll come take a look tomorrow.','明天 places the visit in the future. Offering to inspect the heater is not a claim that the problem has already been fixed.')
 ],[
 q('Which matter is confirmed as completed?',['The rent has been received','The heater has been repaired','The landlord has visited today','The tenant has moved out'],0,[0,1],'The landlord directly confirms receiving the rent. The heater visit is still planned for tomorrow.'),
 q('What is the promised next action?',['Replace the room','Refund all the rent','Come look at the heater tomorrow','Ask the tenant to leave'],2,[2,3],'The tenant raises a possible heater problem, and the landlord promises to come look tomorrow, without promising a specific repair.')
 ],['Recover omitted objects from the previous question.','An inspection promised for tomorrow is not a repair completed today.']),
 mini(36,'Study first, then look for work','notice','Read a short personal plan. Distinguish the sequence from assumptions about how easy it will be.', ['u36-yihou-after','u36-hao-nan-verb','u34-first-then'],[
 line('Plan','我|想|先|念書|，|再|找|工作|。','Wǒ xiǎng xiān niànshū, zài zhǎo gōngzuò.','I want to study first, then look for work.','先…再… places the two activities in order. Looking for work is a future intention, not evidence that a job has already been found.'),
 line('Reason','我|希望|在|這|個|國家|上班|，|可是|工作|不|好|找|。','Wǒ xīwàng zài zhè ge guójiā shàngbān, kěshì gōngzuò bù hǎo zhǎo.','I hope to work in this country, but jobs are not easy to find.','不好找 describes difficulty finding work. It does not mean the jobs themselves are morally bad or necessarily unpleasant.'),
 line('Next step','念|一|年|中文|以後|，|我|想|試|試|。','Niàn yì nián Zhōngwén yǐhòu, wǒ xiǎng shìshi.','After studying Chinese for a year, I’d like to give it a try.','以後 makes a year of study the earlier event and trying the later one. The understood thing to try is the job search from the preceding lines.'),
 line('Friend','加油|！|我|也|覺得|學|中文|很|有意思|。','Jiāyóu! Wǒ yě juéde xué Zhōngwén hěn yǒuyìsi.','Keep going! I also find learning Chinese interesting.','加油 encourages the plan. Enjoying Chinese is supportive, but the friend does not guarantee that finding a job will be easy.')
 ],[
 q('What does 不好找 mean here?',['The job is ugly','Jobs are difficult to find','The speaker refuses to work','The country has no jobs at all'],1,[1],'好 or 不好 before 找 evaluates how easy finding something is; it does not evaluate the quality of the job itself.'),
 q('Which sequence matches the plan?',['Start a job, then learn Chinese','Give up studying to work','Get a guaranteed job tomorrow','Study Chinese, then try looking for work'],3,[0,2],'Both the first-then statement and the 以後 statement place Chinese study before trying the job search.')
 ],['Read 好/不好 + verb as an ease judgment when the taught pattern applies.','Encouragement supports an intention without guaranteeing its result.']),
 mini(39,'A gift bought, a meal not ordered','messages','Read a birthday-planning exchange. Keep buying and ordering separate.', ['u39-verbal-le','u39-bu-vs-mei'],[
 line('Lin','我|買|了|禮物|。|你|訂|了|豬腳|麵線|嗎|？','Wǒ mǎi le lǐwù. Nǐ dìng le zhūjiǎo miànxiàn ma?','I bought a gift. Have you ordered pork-knuckle noodles?','The first 了 marks a completed purchase. The second appears in a question, so it does not confirm a completed food order.'),
 line('Mei','還|沒|訂|。|我|今天|晚上|訂|。','Hái méi dìng. Wǒ jīntiān wǎnshang dìng.','Not yet. I’ll order tonight.','沒訂 denies completion and does not keep verbal 了. The following time expression moves the ordering to a plan for this evening.'),
 line('Lin','好|，|我|們|明天|一起|吃飯|。|我|想|吃|一點|麵線|。','Hǎo, wǒmen míngtiān yìqǐ chīfàn. Wǒ xiǎng chī yìdiǎn miànxiàn.','Okay, we’ll eat together tomorrow. I’d like a little thin-noodle dish.','明天 dates the meal rather than the ordering. 一點 before the food is a small quantity here, not the clock time one o’clock.'),
 line('Mei','沒問題|。|禮物|是|什麼|？','Méi wèntí. Lǐwù shì shénme?','No problem. What is the gift?','The final question asks about the already-bought gift. Since no answer follows, its exact identity remains unknown to the reader.')
 ],[
 q('Which action is already completed?',['Buying the gift','Ordering the noodles','Eating tomorrow’s meal','Giving the gift'],0,[0,1],'Lin states 買了禮物, while Mei explicitly says the noodles have not yet been ordered.'),
 q('What information is still missing?',['When Mei plans to order','When they plan to eat','What the gift actually is','Whether Lin wants some noodles'],2,[1,2,3],'Ordering time, meal time and Lin’s food preference are stated, but the gift question receives no answer.')
 ],['A positive completed action and a question about another action carry different evidence.','Check whether 一點 is followed by a food or used as a clock time.']),
 mini(42,'Two seasons, two different activities','notice','Read two friends’ seasonal notes. Weather preferences explain why their plans differ.', ['u31-yinwei-suoyi','u16-contrast'],[
 line('Mei','冬天|很|冷|，|可是|我|喜歡|冬天|。','Dōngtiān hěn lěng, kěshì wǒ xǐhuān dōngtiān.','Winter is cold, but I like winter.','可是 contrasts the cold weather with a positive preference. Cold does not automatically mean the speaker dislikes the season.'),
 line('Mei','山上|下雪|的|時候|，|我|想|去|滑雪|。','Shānshàng xiàxuě de shíhòu, wǒ xiǎng qù huáxuě.','When it snows in the mountains, I want to go skiing.','的時候 connects the intended activity to snowy conditions. 想 makes skiing a wish rather than a report of an already-completed trip.'),
 line('Lin','我|不|喜歡|冷|的|天氣|。|我|最|喜歡|夏天|。','Wǒ bù xǐhuān lěng de tiānqì. Wǒ zuì xǐhuān xiàtiān.','I don’t like cold weather. Summer is my favorite.','The speaker has changed, so this preference belongs to Lin rather than contradicting Mei’s winter preference.'),
 line('Lin','因為|我|喜歡|游泳|，|所以|夏天|常|和|朋友|去|游泳池|。','Yīnwèi wǒ xǐhuān yóuyǒng, suǒyǐ xiàtiān cháng hé péngyǒu qù yóuyǒngchí.','Because I like swimming, I often go to the pool with friends in summer.','因為 introduces the reason and 所以 the habitual result. 常 describes frequency rather than a single appointment at a fixed time.')
 ],[
 q('Which pairing fits the two writers?',['Mei: summer swimming; Lin: winter skiing','Mei: winter skiing; Lin: summer swimming','Both dislike winter','Both plan a mountain trip tomorrow'],1,[0,1,2,3],'Mei’s winter preference connects to skiing, while Lin’s summer preference connects to swimming.'),
 q('Is Mei reporting a ski trip that already happened?',['Yes, last winter','Yes, yesterday','Yes, with Lin','No; she expresses a wish for snowy conditions'],3,[1],'The line uses 想 and a when-it-snows condition. It gives no completed ski trip or past date.')
 ],['Keep each preference attached to its speaker.','Separate a seasonal habit from a wish and from a completed event.']),
 mini(45,'Yesterday’s cold, today’s symptoms','dialogue','Read a short symptom report. This is a comprehension exercise; the passage does not give a diagnosis.', [],[
 line('Mei','你|今天|怎麼樣|？|昨天|天氣|很|冷|。','Nǐ jīntiān zěnmeyàng? Zuótiān tiānqì hěn lěng.','How are you today? The weather was cold yesterday.','今天 asks about the person now, while 昨天 describes earlier weather. The weather comment alone does not establish a cause of illness.'),
 line('Lin','我|今天|一直|流|鼻水|，|頭|也|很|痛|。','Wǒ jīntiān yìzhí liú bíshuǐ, tóu yě hěn tòng.','My nose keeps running today, and my head really hurts too.','一直 presents the runny nose as continuing. 也 adds a second symptom, so the headache is not the only reported problem.'),
 line('Mei','你|有|沒有|發燒|？|胃口|怎麼樣|？','Nǐ yǒu méiyǒu fāshāo? Wèikǒu zěnmeyàng?','Do you have a fever? How is your appetite?','The first sentence asks whether fever is present, and the second asks about appetite. Neither question supplies its own answer.'),
 line('Lin','沒有|發燒|，|可是|胃口|很|差|。|我|想|去|看|醫生|。','Méiyǒu fāshāo, kěshì wèikǒu hěn chà. Wǒ xiǎng qù kàn yīshēng.','I don’t have a fever, but my appetite is poor. I want to see a doctor.','沒有 denies fever, while 可是 introduces a different problem. 想去 makes the doctor visit an intention, not a completed visit or diagnosis.')
 ],[
 q('Which symptom does Lin explicitly deny?',['Fever','A runny nose','A headache','Poor appetite'],0,[1,2,3],'Lin reports the runny nose, headache and poor appetite, but directly says there is no fever.'),
 q('What can we conclude about seeing a doctor?',['The doctor diagnosed a cold','The visit happened yesterday','Lin wants to go, but no completed visit is stated','Mei is the doctor'],2,[3],'Lin expresses a wish to see a doctor. The passage does not report that a visit or diagnosis has already happened.')
 ],['Keep reported symptoms separate from symptoms mentioned only in questions.','An intention to seek help does not tell you the outcome of a visit.']),
];
