import type {UnitData} from '../schema.ts';

// Textbook-aligned Lesson 8 explicit comparisons; examples are original unless noted by structure.
const unit:UnitData = {
  "schemaVersion":1,"bookId":"book-1","order":24,
  "unit":{"id":"unit-24","number":24,"theme":"amber","label":"Explicit comparisons with 比","title":"Which One Is More?","description":"1 new word/form. Compare familiar things explicitly with 比, ask comparison questions, and negate comparison claims.","chars":[],"lessonIds":["u24-frame","u24-price","u24-distance","u24-degree","u24-negation","u24-questions","u24-review"],"banner":{"text":"這支手機比那支手機貴。","pinyin":"Zhè zhī shǒujī bǐ nà zhī shǒujī guì."},"goal":{"text":"我們學校比他們學校大。","pinyin":"Wǒmen xuéxiào bǐ tāmen xuéxiào dà.","meaning":"Our school is bigger than their school."},"grammarIds":["u24-bi-comparison","u24-bi-degree","u24-bi-negation"],"bookReference":"A Course in Contemporary Chinese 1 · Lesson 8, pp. 169–174. Explicit comparison with 比; original Hanzi Steps examples."},
  "reviewLessonId":"u24-review",
  "lessons":[
    {"id":"u24-frame","title":"A 比 B","subtitle":"Build the basic explicit comparison frame.","chars":[],"minutes":"7–9 min","unitId":"unit-24","review":false,"steps":[{"id":"u24-frame-01","type":"grammar","grammar":"u24-bi-comparison"},{"id":"u24-frame-02","type":"phrase","phrase":"u24-school-big"},{"id":"u24-frame-03","type":"order","phrase":"u24-school-big","tokens":["大","他們學校","比","我們學校"]},{"id":"u24-frame-04","type":"phrase","phrase":"u24-book-big"},{"id":"u24-frame-05","type":"order","phrase":"u24-book-big","tokens":["大","那本書","比","這本書"]},{"id":"u24-frame-06","type":"select","prompt":"In A 比 B + property, what follows 比?","options":["the comparison standard B","the property","嗎"],"answer":"the comparison standard B","explanation":"比 introduces the item used as the comparison standard.","grammarIds":["u24-bi-comparison"]},{"id":"u24-frame-07","type":"select","prompt":"Which means “This book is bigger than that book”?","options":["這本書比那本書大。","那本書比這本書大。"],"answer":"這本書比那本書大。","explanation":"The item described as bigger must be A, before 比.","grammarIds":["u24-bi-comparison"]}]},
    {"id":"u24-price","title":"Compare Prices","subtitle":"Use 比 with familiar phone and price language.","chars":[],"minutes":"7–9 min","unitId":"unit-24","review":false,"steps":[{"id":"u24-price-01","type":"phrase","phrase":"u24-phone-expensive"},{"id":"u24-price-02","type":"order","phrase":"u24-phone-expensive","tokens":["貴","那支手機","比","這支手機"]},{"id":"u24-price-03","type":"phrase","phrase":"u24-question"},{"id":"u24-price-04","type":"order","phrase":"u24-question","tokens":["嗎","貴","那支手機","比","這支手機"]},{"id":"u24-price-05","type":"select","prompt":"Which phone is described as more expensive in 這支手機比那支手機貴？","options":["this phone","that phone"],"answer":"this phone","explanation":"A before 比 is the item receiving the comparison.","grammarIds":["u24-bi-comparison"]},{"id":"u24-price-06","type":"select","prompt":"Can 很 go directly before 貴 in the basic 比 pattern taught here?","options":["No","Yes"],"answer":"No","explanation":"The textbook notes that degree adverbs such as 很 do not appear before the state verb in this basic 比 comparison.","grammarIds":["u24-bi-degree"]}]},
    {"id":"u24-distance","title":"Nearer or Farther","subtitle":"Transfer the same frame to distance.","chars":[],"minutes":"7–9 min","unitId":"unit-24","review":false,"steps":[{"id":"u24-distance-01","type":"phrase","phrase":"u24-store-near"},{"id":"u24-distance-02","type":"order","phrase":"u24-store-near","tokens":["近","那個商店","比","這個商店"]},{"id":"u24-distance-03","type":"phrase","phrase":"u24-school-far"},{"id":"u24-distance-04","type":"order","phrase":"u24-school-far","tokens":["遠","我們學校","比","他們學校"]},{"id":"u24-distance-05","type":"select","prompt":"Which property means “far”?","options":["遠","近","大"],"answer":"遠","explanation":"遠 is far; 近 is near."},{"id":"u24-distance-06","type":"select","prompt":"Choose the sentence that says their school is farther.","options":["他們學校比我們學校遠。","我們學校比他們學校遠。"],"answer":"他們學校比我們學校遠。","explanation":"The farther school is A before 比.","grammarIds":["u24-bi-comparison"]}]},
    {"id":"u24-degree","title":"No 很 Inside the Basic 比 Frame","subtitle":"Avoid a common comparison word-order error.","chars":[],"minutes":"7–9 min","unitId":"unit-24","review":false,"steps":[{"id":"u24-degree-01","type":"grammar","grammar":"u24-bi-degree"},{"id":"u24-degree-02","type":"phrase","phrase":"u24-phone-expensive"},{"id":"u24-degree-03","type":"select","prompt":"Choose the textbook-style comparison.","options":["這支手機比那支手機貴。","這支手機比那支手機很貴。"],"answer":"這支手機比那支手機貴。","explanation":"The basic 比 pattern does not insert 很 before the property.","grammarIds":["u24-bi-degree"]},{"id":"u24-degree-04","type":"phrase","phrase":"u24-book-big"},{"id":"u24-degree-05","type":"order","phrase":"u24-book-big","tokens":["大","那本書","比","這本書"]},{"id":"u24-degree-06","type":"select","prompt":"Which is the basic pattern?","options":["A 比 B + property","A 比 B 很 + property"],"answer":"A 比 B + property","explanation":"Use the state verb/property directly after B.","grammarIds":["u24-bi-degree"]}]},
    {"id":"u24-negation","title":"Negate a Comparison","subtitle":"Put 不 before 比 or reject the whole claim with 不是比.","chars":[],"minutes":"8–10 min","unitId":"unit-24","review":false,"steps":[{"id":"u24-negation-01","type":"grammar","grammar":"u24-bi-negation"},{"id":"u24-negation-02","type":"phrase","phrase":"u24-not-more-expensive"},{"id":"u24-negation-03","type":"order","phrase":"u24-not-more-expensive","tokens":["貴","他的手機","不比","我的手機"]},{"id":"u24-negation-04","type":"phrase","phrase":"u24-not-case"},{"id":"u24-negation-05","type":"order","phrase":"u24-not-case","tokens":["大","那本書","不是比","這本書"]},{"id":"u24-negation-06","type":"select","prompt":"Where does 不 go in the direct negative comparison?","options":["before 比","after B","after the property"],"answer":"before 比","explanation":"The textbook gives A 不比 B + property.","grammarIds":["u24-bi-negation"]}]},
    {"id":"u24-questions","title":"Ask About the Comparison","subtitle":"Turn an explicit comparison into a yes/no question.","chars":[],"minutes":"6–8 min","unitId":"unit-24","review":false,"steps":[{"id":"u24-questions-01","type":"phrase","phrase":"u24-question"},{"id":"u24-questions-02","type":"order","phrase":"u24-question","tokens":["嗎","貴","那支手機","比","這支手機"]},{"id":"u24-questions-03","type":"select","prompt":"What does 嗎 do here?","options":["asks whether the comparison is true","makes B larger","negates 比"],"answer":"asks whether the comparison is true","explanation":"The comparison remains intact; 嗎 makes it a yes/no question.","grammarIds":["u24-bi-comparison"]},{"id":"u24-questions-04","type":"phrase","phrase":"u24-store-near"},{"id":"u24-questions-05","type":"select","prompt":"Which question asks whether this phone is more expensive?","options":["這支手機比那支手機貴嗎？","這支手機比那支手機嗎貴？"],"answer":"這支手機比那支手機貴嗎？","explanation":"Sentence-final 嗎 follows the complete comparison.","grammarIds":["u24-bi-comparison"]}]},
    {"id":"u24-review","title":"Unit 24 Review","subtitle":"Build, interpret, question, and negate explicit 比 comparisons.","chars":[],"minutes":"8–10 min","unitId":"unit-24","review":true,"steps":[{"id":"u24-review-01","type":"phrase","phrase":"u24-school-big"},{"id":"u24-review-02","type":"order","phrase":"u24-school-big","tokens":["大","他們學校","比","我們學校"]},{"id":"u24-review-03","type":"phrase","phrase":"u24-phone-expensive"},{"id":"u24-review-04","type":"order","phrase":"u24-phone-expensive","tokens":["貴","那支手機","比","這支手機"]},{"id":"u24-review-05","type":"select","prompt":"Choose the correct comparison.","options":["這個商店比那個商店近。","這個商店比那個商店很近。"],"answer":"這個商店比那個商店近。","explanation":"Use the property directly in the basic 比 frame.","grammarIds":["u24-bi-degree"]},{"id":"u24-review-06","type":"select","prompt":"Choose the direct negative comparison.","options":["我的手機不比他的手機貴。","我的手機比不他的手機貴。"],"answer":"我的手機不比他的手機貴。","explanation":"不 precedes 比.","grammarIds":["u24-bi-negation"]},{"id":"u24-review-07","type":"select","prompt":"In 我們學校比他們學校大, which school is bigger?","options":["our school","their school"],"answer":"our school","explanation":"A before 比 is described as having more of the property.","grammarIds":["u24-bi-comparison"]},{"id":"u24-review-08","type":"phrase","phrase":"u24-question"}]}
  ],
  "newVocabulary":[{"text":"比","pinyin":"bǐ","meaning":"than; compared with","lessonId":"u24-frame","core":true,"note":"Preposition introducing the comparison standard in A 比 B + property."}],
  "reviewVocabulary":["我","我們","他","他們","的","這","那","本","書","大","手機","支","貴","商店","近","遠","不","是","嗎"],
  "newCharacters":[],"reviewCharacters":[],"characters":{},
  "grammarRules":{
    "u24-bi-comparison":{"id":"u24-bi-comparison","title":"Explicit comparison with 比","pattern":"A + 比 + B + State Verb / Property","explanation":"比 introduces the comparison standard B. The item being described is A, before 比, and the property comes after B. This explicitly says A has more of that property than B.","examples":[{"text":"我們學校比他們學校大。","pinyin":"Wǒmen xuéxiào bǐ tāmen xuéxiào dà.","meaning":"Our school is bigger than their school."},{"text":"這支手機比那支手機貴。","pinyin":"Zhè zhī shǒujī bǐ nà zhī shǒujī guì.","meaning":"This phone is more expensive than that phone."}],"remember":"A is the item you are describing; B is the comparison standard after 比.","words":["比"]},
    "u24-bi-degree":{"id":"u24-bi-degree","title":"Keep 很 out of the basic 比 comparison","pattern":"A + 比 + B + Property  ✓","explanation":"In the textbook's basic 比 pattern, degree adverbs such as 很, 真, and 非常 do not appear directly before the state verb/property. Say A 比 B 貴, not A 比 B 很貴.","examples":[{"text":"這支手機比那支手機貴。","pinyin":"Zhè zhī shǒujī bǐ nà zhī shǒujī guì.","meaning":"This phone is more expensive than that phone."},{"text":"這本書比那本書大。","pinyin":"Zhè běn shū bǐ nà běn shū dà.","meaning":"This book is bigger than that book."}],"remember":"Basic 比 frame: go straight from B to the property.","words":["比"]},
    "u24-bi-negation":{"id":"u24-bi-negation","title":"Negating 比 comparisons","pattern":"A + 不比 + B + Property / A + 不是比 + B + Property","explanation":"The textbook allows the 比 comparison to be negated with 不 before 比. 不是比 can reject the comparison claim as a whole. Keep the comparison order intact.","examples":[{"text":"我的手機不比他的手機貴。","pinyin":"Wǒ de shǒujī bù bǐ tā de shǒujī guì.","meaning":"My phone is not more expensive than his."},{"text":"這本書不是比那本書大。","pinyin":"Zhè běn shū bú shì bǐ nà běn shū dà.","meaning":"It is not the case that this book is bigger than that book."}],"remember":"Direct negation: 不 + 比. Whole-claim correction: 不是 + 比.","words":["不","不是","比"]}
  },
  "grammarIntroductions":[{"id":"u24-bi-comparison","kind":"rule","ref":"u24-bi-comparison","lessonId":"u24-frame","stepId":"u24-frame-01"},{"id":"u24-bi-degree","kind":"rule","ref":"u24-bi-degree","lessonId":"u24-degree","stepId":"u24-degree-01"},{"id":"u24-bi-negation","kind":"rule","ref":"u24-bi-negation","lessonId":"u24-negation","stepId":"u24-negation-01"}],
  "reviewGrammar":[],
  "phrases":{
    "u24-school-big":{"text":"我們學校比他們學校大。","pinyin":"Wǒmen xuéxiào bǐ tāmen xuéxiào dà.","meaning":"Our school is bigger than their school.","note":"A comes before 比; B follows 比; the property comes last.","tokens":["我們學校","比","他們學校","大"],"grammarIds":["u24-bi-comparison"]},
    "u24-book-big":{"text":"這本書比那本書大。","pinyin":"Zhè běn shū bǐ nà běn shū dà.","meaning":"This book is bigger than that book.","note":"The compared items occupy A and B; 大 is the property.","tokens":["這本書","比","那本書","大"],"grammarIds":["u24-bi-comparison"]},
    "u24-phone-expensive":{"text":"這支手機比那支手機貴。","pinyin":"Zhè zhī shǒujī bǐ nà zhī shǒujī guì.","meaning":"This phone is more expensive than that phone.","note":"比 marks the comparison standard before the state verb 貴.","tokens":["這支手機","比","那支手機","貴"],"grammarIds":["u24-bi-comparison"]},
    "u24-store-near":{"text":"這個商店比那個商店近。","pinyin":"Zhè ge shāngdiàn bǐ nà ge shāngdiàn jìn.","meaning":"This shop is closer than that shop.","note":"近 is the compared property.","tokens":["這個商店","比","那個商店","近"],"grammarIds":["u24-bi-comparison"]},
    "u24-school-far":{"text":"他們學校比我們學校遠。","pinyin":"Tāmen xuéxiào bǐ wǒmen xuéxiào yuǎn.","meaning":"Their school is farther than our school.","note":"遠 comes after the B comparison standard.","tokens":["他們學校","比","我們學校","遠"],"grammarIds":["u24-bi-comparison"]},
    "u24-not-more-expensive":{"text":"我的手機不比他的手機貴。","pinyin":"Wǒ de shǒujī bù bǐ tā de shǒujī guì.","meaning":"My phone is not more expensive than his.","note":"不 comes before 比 to negate the comparative claim.","tokens":["我的手機","不比","他的手機","貴"],"grammarIds":["u24-bi-negation"]},
    "u24-not-case":{"text":"這本書不是比那本書大。","pinyin":"Zhè běn shū bú shì bǐ nà běn shū dà.","meaning":"It is not the case that this book is bigger than that book.","note":"不是比 rejects the comparison claim as a whole.","tokens":["這本書","不是比","那本書","大"],"grammarIds":["u24-bi-negation"]},
    "u24-question":{"text":"這支手機比那支手機貴嗎？","pinyin":"Zhè zhī shǒujī bǐ nà zhī shǒujī guì ma?","meaning":"Is this phone more expensive than that phone?","note":"Add 嗎 to ask whether the comparison is true.","tokens":["這支手機","比","那支手機","貴","嗎"],"grammarIds":["u24-bi-comparison"]}
  },
  "revisionStepIds":["u24-price-01","u24-distance-01","u24-review-03"]
};

export default unit;
