'use client';
import {useEffect,useId,useRef,useState} from 'react';
import type HanziWriter from 'hanzi-writer';
import {Eye,Lightbulb,Play,RotateCcw,Check} from 'lucide-react';
import {strokeData} from './character-art';
import {createWriterTarget} from '@/lib/writer-target';
import {useInteractionFeedback} from './interaction-feedback';
export type WriteMode='intro'|'trace'|'complete'|'memory';
export function WritingPad({char,mode,onComplete}:{char:string;mode:WriteMode;onComplete?:(assisted:boolean)=>void}){
 const {feedback:feel}=useInteractionFeedback();
 const host=useRef<HTMLDivElement>(null);const writer=useRef<HanziWriter|null>(null);const callback=useRef(onComplete);callback.current=onComplete;
 const start=mode==='complete'?Math.max(0,strokeData[char].strokes.length-3):0;
 const [next,setNext]=useState(start);const nextRef=useRef(start);const [ready,setReady]=useState(false);const [failed,setFailed]=useState(false);const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);const [guide,setGuide]=useState(false);const [message,setMessage]=useState('');const [studyReady,setStudyReady]=useState(false);const [size,setSize]=useState(320);const helped=useRef(false);const misses=useRef(0);const mounted=useRef(true);const [reset,setReset]=useState(0);const marker=useId().replace(/:/g,'');
 const finish=(assisted:boolean)=>{setDone(true);setMessage(assisted?'Finished with support. Keep practicing.':mode==='memory'?'Written from memory!':'All strokes complete!');callback.current?.(assisted)};
 const startQuiz=()=>{const w=writer.current;if(!w)return;nextRef.current=start;setNext(start);setDone(false);setGuide(false);setStudyReady(false);setMessage('');void w.quiz({quizStartStrokeNum:start,leniency:1.25,acceptBackwardsStrokes:false,markStrokeCorrectAfterMisses:false,showHintAfterMisses:2,onMistake:s=>{if(!mounted.current)return;misses.current++;setMessage(s.isBackwards?'Right shape—try the other direction.':'Try that stroke again. Start at the dot.');setGuide(true);helped.current=true},onCorrectStroke:s=>{if(!mounted.current)return;nextRef.current=s.strokeNum+1;setNext(s.strokeNum+1);if(s.strokesRemaining)feel('stroke');setGuide(false);setMessage(s.strokesRemaining?'Good. Keep going.':'')},onComplete:s=>{if(mounted.current)finish(helped.current||s.totalMistakes>0||misses.current>0)}})};
 const quizRef=useRef(startQuiz);quizRef.current=startQuiz;
 useEffect(()=>{
  mounted.current=true;let alive=true;let observer:ResizeObserver|undefined;let dispose:(()=>void)|undefined;
  setReady(false);setFailed(false);setDone(false);setBusy(false);setNext(start);nextRef.current=start;setMessage('');setStudyReady(false);setGuide(false);helped.current=false;misses.current=0;
  import('hanzi-writer').then(({default:Hanzi})=>{
   if(!alive||!host.current)return;host.current.replaceChildren();const width=Math.min(320,host.current.clientWidth||320);setSize(width);
   const owned=createWriterTarget(host.current,width,width);dispose=owned.dispose;
   const accent=getComputedStyle(host.current).getPropertyValue('--unit-accent').trim()||'#245ee8';
   const instance=Hanzi.create(host.current,char,{width,height:width,padding:24,showCharacter:mode==='intro',showOutline:mode==='trace',strokeColor:'#172642',outlineColor:'#dfe6f2',drawingColor:accent,drawingWidth:9,highlightColor:accent,highlightCompleteColor:'#24976a',strokeAnimationSpeed:.9,delayBetweenStrokes:220,strokeFadeDuration:120,rendererOverride:{createRenderTarget:()=>owned.target},charDataLoader:()=>strokeData[char]});
   writer.current=instance;
   void instance.getCharacterData().then(()=>{if(!alive)return;setReady(true);if(mode!=='intro')quizRef.current()});
   observer=new ResizeObserver(()=>{if(!host.current||!alive)return;const width=Math.min(320,host.current.clientWidth);if(width>0){setSize(width);void instance.updateDimensions({width,height:width,padding:24})}});observer.observe(host.current);
  }).catch(()=>{if(alive)setFailed(true)});
  return ()=>{alive=false;mounted.current=false;observer?.disconnect();writer.current?.cancelQuiz();writer.current?.pauseAnimation();writer.current=null;dispose?.()};
 },[char,mode,reset,start]);
 async function watch(study=false){const w=writer.current;if(!w||busy)return;if(mode!=='intro')helped.current=true;setBusy(true);setGuide(false);setMessage('Watch the order and direction.');w.cancelQuiz();await w.animateCharacter();if(!mounted.current)return;setBusy(false);if(study){setStudyReady(true);setMessage('Animation studied. You can continue without a handwriting score.')}else if(mode!=='intro'){quizRef.current();setMessage('Your turn. Start again from the first missing stroke.')}else setMessage('Write each stroke in one movement.')}
 function hint(){if(!writer.current||done||busy)return;helped.current=true;setGuide(true);void writer.current.highlightStroke(nextRef.current);setMessage('Start at the dot and follow the arrow.')}
 function reveal(){if(!writer.current||busy||done)return;helped.current=true;void writer.current.showOutline();setMessage('The outline is visible. This attempt will be marked as supported.')}
 const pts=strokeData[char].medians[next];const scale=(size-48)/1024;const x=24;const y=24+900*scale;
 return <div className="writing-area"><div className={`writing-frame ${done?'is-done':''}`}><div ref={host} className="writing-target" aria-label={`Writing area for ${char}. Draw using a finger, mouse, or pen.`} role="group"/>{!ready&&!failed&&<div className="pad-overlay">Loading practice…</div>}{failed&&<div className="pad-overlay"><p>Practice could not load.</p><button className="secondary-button" onClick={()=>setReset(r=>r+1)}>Try again</button></div>}{ready&&!busy&&!done&&mode!=='intro'&&(mode==='trace'||guide)&&pts&&<svg className="stroke-guide" viewBox={`0 0 ${size} ${size}`} aria-hidden="true"><defs><marker id={marker} markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z" fill="var(--unit-accent)"/></marker></defs><polyline points={pts.map(p=>`${x+p[0]*scale},${y-p[1]*scale}`).join(' ')} fill="none" stroke="var(--unit-accent)" strokeWidth="2" strokeDasharray="4 5" markerEnd={`url(#${marker})`} opacity=".8"/><circle cx={x+pts[0][0]*scale} cy={y-pts[0][1]*scale} r="7" fill="var(--unit-accent)" stroke="white" strokeWidth="2"/></svg>}{done&&<span className="pad-check"><Check size={18}/></span>}</div><div className="stroke-status" aria-live="polite">{mode==='intro'?`${strokeData[char].strokes.length} strokes · Taiwan stroke order`:done?'Character complete':`${Math.min(next+1,strokeData[char].strokes.length)} of ${strokeData[char].strokes.length} strokes`}</div><div className="pad-actions">{mode==='intro'?<button className="secondary-button" disabled={!ready||busy} onClick={()=>void watch()}><Play size={17}/>{busy?'Watch the strokes…':'Watch stroke order'}</button>:!done&&<><button className="text-button" onClick={hint} disabled={!ready||busy}><Lightbulb size={17}/>Hint</button><button className="text-button" onClick={()=>void watch()} disabled={!ready||busy}><RotateCcw size={17}/>Watch & restart</button>{mode==='memory'&&<button className="text-button" onClick={reveal} disabled={!ready||busy}><Eye size={17}/>Outline</button>}</>}</div><p className={`pad-message ${done?'positive':''}`} aria-live="polite">{message|| (mode==='trace'?'Trace each stroke from the dot to the arrow.':mode==='complete'?`Finish the last ${Math.min(3,strokeData[char].strokes.length)} ${strokeData[char].strokes.length===1?'stroke':'strokes'}.`:mode==='memory'?'Draw each stroke in order. Hints are here if you need them.':'Tap play to see how the character is written.')}</p>{mode!=='intro'&&!done&&<details className="drawing-alternative"><summary>Using a keyboard or unable to draw?</summary><p>You can study the animation. This counts as supported practice, not independent handwriting.</p><button className="text-button" disabled={!ready||busy} onClick={()=>void watch(true)}><Play size={15}/>Study the animation</button>{studyReady&&<button className="secondary-button" onClick={()=>finish(true)}>Continue as studied</button>}</details>}</div>
}
