// Isolated display metadata; does not register main-course introductions.
export const extraCharacterInfo:Record<string,{pinyin:string;meaning:string;note:string}>={
'恤':{pinyin:'xù',meaning:'T-shirt character',note:'Recognize 恤 after the Latin T in T恤. 忄 is the heart radical on the left; 血 is on the right. The garment word is the full T恤, not 恤 alone.'},
'件':{pinyin:'jiàn',meaning:'measure word for garments',note:'Use 件 for individual garments such as 襯衫 and 外套. 亻 is on the left; 牛 is on the right.'},
'襯':{pinyin:'chèn',meaning:'shirt character; lining',note:'The first character in 襯衫. 衤 is the clothing radical on the left; 親 is on the right.'},
'衫':{pinyin:'shān',meaning:'shirt; light upper garment',note:'The second character in 襯衫. Notice the clothing radical 衤 on the left and three diagonal strokes 彡 on the right.'},
'外':{pinyin:'wài',meaning:'outside; outer',note:'In 外套, 外 points to an outer layer. Notice 夕 on the left and 卜 on the right.'},
'套':{pinyin:'tào',meaning:'cover; set; coat character',note:'Learn 外套 as the full word for an outer garment. 大 sits at the top of 套.'},
'毛':{pinyin:'máo',meaning:'hair; wool',note:'In 毛衣, part of the word for a sweater. The bent final stroke distinguishes 毛 from 手.'},
'衣':{pinyin:'yī',meaning:'clothing',note:'The full character 衣 can become the clothing radical 衤 on the left of 褲, 裙, and 襪.'},
'褲':{pinyin:'kù',meaning:'trousers',note:'The first character in 褲子. 衤 signals clothing; 庫 is on the right.'},
'子':{pinyin:'zǐ',meaning:'child; noun suffix',note:'子 is neutral-tone zi in 褲子, 裙子, 鞋子, 襪子, 帽子, 橘子, and 梨子. Its standalone reading is zǐ.'},
'條':{pinyin:'tiáo',meaning:'measure word for long items',note:'Use 條 with 褲子 and 裙子 here. Notice the wood component 木 in the lower right.'},
'裙':{pinyin:'qún',meaning:'skirt',note:'The first character in 裙子. 衤 is the clothing radical; 君 is on the right.'},
'洋':{pinyin:'yáng',meaning:'ocean; dress character',note:'In Taiwan, 洋裝 means a dress. 氵 is on the left; 羊 is on the right. Learn the full clothing word.'},
'裝':{pinyin:'zhuāng',meaning:'dress; clothing; equip',note:'The second character in 洋裝. Look for 衣 in the bottom part.'},
'鞋':{pinyin:'xié',meaning:'shoe',note:'The first character in 鞋子. 革 is on the left; two stacked 土 shapes form 圭 on the right.'},
'雙':{pinyin:'shuāng',meaning:'pair; double',note:'Use 雙 for a pair of shoes or socks. The repeated 隹 shapes at the top help you remember two.'},
'襪':{pinyin:'wà',meaning:'sock',note:'The first character in 襪子. The clothing radical 衤 is on the left; 蔑 is on the right.'},
'帽':{pinyin:'mào',meaning:'hat; cap',note:'The first character in 帽子. 巾 is on the left; 冒 is on the right.'},
'頂':{pinyin:'dǐng',meaning:'top; measure word for hats',note:'Use 頂 for hats and caps. 丁 is on the left; 頁 is on the right.'},
'蘋':{pinyin:'píng',meaning:'apple character',note:'The first character in 蘋果. 艹 at the top marks a plant-related character; 頻 sits underneath.'},
'果':{pinyin:'guǒ',meaning:'fruit; result',note:'Shared by 蘋果 and 芒果. Notice the box-shaped upper part over 木.'},
'個':{pinyin:'gè',meaning:'general measure word',note:'A common counting word for whole fruit. Often pronounced lightly as ge in counting phrases. 亻 is on the left; 固 is on the right.'},
'香':{pinyin:'xiāng',meaning:'fragrant',note:'The first character in 香蕉. 禾 sits above 日.'},
'蕉':{pinyin:'jiāo',meaning:'banana character',note:'The second character in 香蕉. 艹 sits above 焦; notice 灬 at the bottom.'},
'根':{pinyin:'gēn',meaning:'root; measure word for long items',note:'Use 根 for an individual banana here. 木 is on the left; 艮 is on the right.'},
'橘':{pinyin:'jú',meaning:'mandarin orange; tangerine',note:'The first character in 橘子. 木 is on the left; 矞 is on the right.'},
'葡':{pinyin:'pú',meaning:'grape character',note:'The first character in 葡萄. 艹 is at the top; 匍 is underneath. Learn 葡萄 as one fruit word.'},
'萄':{pinyin:'táo',meaning:'grape character',note:'The second character in 葡萄. 艹 is at the top; 匋 is underneath.'},
'串':{pinyin:'chuàn',meaning:'string; bunch; measure word',note:'Use 串 for a bunch of grapes. A vertical stroke runs through two box shapes: think of items joined on a string.'},
'西':{pinyin:'xī',meaning:'west',note:'In 西瓜, part of the established word for watermelon. Learn the complete fruit word; it does not mean a western fruit.'},
'瓜':{pinyin:'guā',meaning:'melon; gourd',note:'Shared by 西瓜 and 木瓜. Keep the central and outer strokes distinct.'},
'鳳':{pinyin:'fèng',meaning:'phoenix; pineapple character',note:'The first character in the Taiwan word 鳳梨. Notice the outer frame and bird-shaped interior.'},
'梨':{pinyin:'lí',meaning:'pear',note:'梨子 is pear; 鳳梨 is pineapple. 利 sits above 木. The meaning depends on the full word.'},
'芒':{pinyin:'máng',meaning:'mango character; awn',note:'The first character in 芒果. 艹 sits above 亡.'},
'草':{pinyin:'cǎo',meaning:'grass',note:'The first character in 草莓. 艹 sits above 早.'},
'莓':{pinyin:'méi',meaning:'berry',note:'The second character in 草莓. 艹 sits above 每.'},
'顆':{pinyin:'kē',meaning:'measure word for small round items',note:'Use 顆 for strawberries or individual grapes. 果 is on the left; 頁 is on the right. A whole bunch of grapes uses 串.'},
'木':{pinyin:'mù',meaning:'tree; wood',note:'The first character in 木瓜, papaya. Also appears as a component in 梨 and 橘.'},
'短':{"pinyin":"duǎn","meaning":"short","note":"短褲 means shorts; the left part is 矢 and the right part is 豆."},
'牛':{"pinyin":"niú","meaning":"cow; ox","note":"In 牛仔褲, part of the full word for jeans. Keep the horizontal strokes and vertical stroke distinct."},
'仔':{"pinyin":"zǎi","meaning":"jeans character","note":"Read 仔 as zǎi in 牛仔褲. It also has other readings in other words. 亻 is beside 子."},
'運':{"pinyin":"yùn","meaning":"transport; movement","note":"In 運動鞋, 運動 means sport or exercise. 辶 surrounds 軍."},
'動':{"pinyin":"dòng","meaning":"move","note":"The second character of 運動. Notice 重 on the left and 力 on the right."},
'雨':{"pinyin":"yǔ","meaning":"rain","note":"雨衣 is a raincoat. Notice the four small strokes inside the frame."},
'泳':{"pinyin":"yǒng","meaning":"swim","note":"泳衣 is a swimsuit. 氵 is beside 永."},
'圍':{"pinyin":"wéi","meaning":"surround","note":"圍巾 is scarf. The outer enclosure 囗 surrounds 韋."},
'巾':{"pinyin":"jīn","meaning":"cloth","note":"In 圍巾, part of the scarf word. Also appears on the left of 帽."},
'手':{"pinyin":"shǒu","meaning":"hand","note":"手套 means gloves. Contrast the final hooked stroke of 手 with 毛."},
'皮':{"pinyin":"pí","meaning":"skin; leather","note":"皮帶 means belt. Learn the complete word; belts can be made from different materials."},
'帶':{"pinyin":"dài","meaning":"belt; carry","note":"The second character in 皮帶. Notice 巾 at the bottom."},
'眼':{"pinyin":"yǎn","meaning":"eye","note":"眼鏡 means eyeglasses. 目 is on the left; 艮 on the right."},
'鏡':{"pinyin":"jìng","meaning":"mirror; lens","note":"The second character in 眼鏡. 金 changes to 釒 on the left, beside 竟."},
'副':{"pinyin":"fù","meaning":"measure word for a set","note":"一副眼鏡 is one set of eyeglasses. The right side is 刂."},
'背':{"pinyin":"bèi / bēi","meaning":"back; carry on the back","note":"背包 is bèibāo, backpack. The verb 背 is bēi in 我背背包. Notice 北 above 月."},
'包':{"pinyin":"bāo","meaning":"bag; wrap","note":"背包 means backpack. Notice the outer 勹 wrapping 巳."},
'穿':{"pinyin":"chuān","meaning":"wear clothing or footwear","note":"Use 穿 for garments and shoes. 穴 sits above 牙."},
'戴':{"pinyin":"dài","meaning":"wear an accessory","note":"Use 戴 for hats, scarves, gloves, and eyeglasses. Follow the stroke demonstration to distinguish its dense upper and lower parts."},
'隻':{"pinyin":"zhī","meaning":"measure word for one individual item","note":"一隻鞋子 is one shoe; 一雙鞋子 names a pair. 隹 sits above 又."},
'芭':{"pinyin":"bā","meaning":"guava character","note":"芭樂 is a common Taiwan word for guava. 艹 sits above 巴."},
'樂':{"pinyin":"lè","meaning":"guava character; joy","note":"Read 樂 as lè in 芭樂. It has other readings in other words. Notice 木 at the bottom."},
'火':{"pinyin":"huǒ","meaning":"fire","note":"火龍果 means dragon fruit. Notice its central strokes and two side dots."},
'龍':{"pinyin":"lóng","meaning":"dragon","note":"The middle character of 火龍果. Study the traditional form 龍 in stroke order."},
'奇':{"pinyin":"qí","meaning":"unusual; kiwi character","note":"奇異果 means kiwifruit. 大 sits above 可."},
'異':{"pinyin":"yì","meaning":"different; kiwi character","note":"The middle character of 奇異果. Notice the upper 田 shape."},
'柳':{"pinyin":"liǔ","meaning":"willow; orange character","note":"柳橙 is sweet orange. 木 is beside 卯."},
'橙':{"pinyin":"chéng","meaning":"orange","note":"柳橙 names a sweet orange; 橘子 names a mandarin or tangerine. 木 is beside 登."},
'檸':{"pinyin":"níng","meaning":"lemon character","note":"The first character in 檸檬. 木 is beside 寧."},
'檬':{"pinyin":"méng","meaning":"lemon character","note":"The second character in 檸檬. 木 is beside 蒙."},
'桃':{"pinyin":"táo","meaning":"peach","note":"桃子 is peach; 櫻桃 is cherry. 木 is beside 兆."},
'李':{"pinyin":"lǐ","meaning":"plum","note":"李子 is lǐzi, plum. 梨子 is lízi, pear: listen to the different first tones. 木 sits above 子."},
'櫻':{"pinyin":"yīng","meaning":"cherry character","note":"櫻桃 means cherry. 木 is beside 嬰."},
'荔':{"pinyin":"lì","meaning":"lychee character","note":"The first character in 荔枝. 艹 sits above three 力 shapes."},
'枝':{"pinyin":"zhī","meaning":"branch; lychee character","note":"The second character in 荔枝. 木 is beside 支."},
'柚':{"pinyin":"yòu","meaning":"pomelo","note":"柚子 is pomelo; 葡萄柚 is grapefruit. 木 is beside 由."},
'片':{"pinyin":"piàn","meaning":"slice; measure word","note":"一片西瓜 is one slice of watermelon. Use 片 for the slice, not a whole fruit."},
'塊':{"pinyin":"kuài","meaning":"piece; chunk; measure word","note":"一塊鳳梨 is one piece of pineapple. 土 is beside 鬼."},
'盒':{"pinyin":"hé","meaning":"box; measure word","note":"一盒草莓 is one box of strawberries. 合 sits above 皿."},
'公':{"pinyin":"gōng","meaning":"public; kilogram character","note":"公斤 means kilogram. Learn the weight unit as one word. 八 sits above 厶."},
'斤':{"pinyin":"jīn","meaning":"weight unit","note":"公斤 is kilogram. In Taiwan market phrases, 斤 usually means 台斤, 600 g. Follow the diagonal and vertical strokes in the demonstration."},
'紅':{"pinyin":"hóng","meaning":"red","note":"紅色 is red. 糹 is beside 工."},
'色':{"pinyin":"sè","meaning":"color","note":"Color names often end in 色. Notice the small upper part over 巴."},
'黃':{"pinyin":"huáng","meaning":"yellow","note":"黃色 is yellow. Follow the central box and lower strokes in order."},
'綠':{"pinyin":"lǜ","meaning":"green","note":"綠色 is green. Keep the ü sound in lǜ. 糹 is beside 彔."},
'藍':{"pinyin":"lán","meaning":"blue","note":"藍色 is blue; 深藍色 is dark blue and 淺藍色 is light blue. 艹 sits above 監."},
'紫':{"pinyin":"zǐ","meaning":"purple","note":"紫色 is purple. 此 sits above 糸."},
'粉':{"pinyin":"fěn","meaning":"powder; pink character","note":"粉紅色 is pink. 米 is beside 分. Learn the full color name."},
'咖':{"pinyin":"kā","meaning":"coffee character","note":"咖啡色 is brown. 口 is beside 加. 咖啡 also names coffee."},
'啡':{"pinyin":"fēi","meaning":"coffee character","note":"The second character in 咖啡色. 口 is beside 非."},
'黑':{"pinyin":"hēi","meaning":"black","note":"黑色 is black. Notice 灬 at the bottom."},
'白':{"pinyin":"bái","meaning":"white","note":"白色 is white. A short diagonal stroke sits above the box shape."},
'灰':{"pinyin":"huī","meaning":"gray; ash","note":"灰色 is gray. Notice 火 beneath the outer strokes."},
'金':{"pinyin":"jīn","meaning":"gold; metal","note":"金色 means gold-colored appearance; it does not specify an object’s material. 金 becomes 釒 on the left of 銀 and 鏡."},
'銀':{"pinyin":"yín","meaning":"silver","note":"銀色 means silver-colored appearance. 釒 is beside 艮."},
'深':{"pinyin":"shēn","meaning":"deep; dark","note":"深 makes a color darker: 深藍色. 氵 is on the left."},
'淺':{"pinyin":"qiǎn","meaning":"shallow; light-colored","note":"淺 makes a color lighter or paler: 淺藍色. 氵 is beside 戔."},
'顏':{"pinyin":"yán","meaning":"color; face","note":"顏色 means color. 頁 is on the right. Learn the complete word."},
'種':{"pinyin":"zhǒng","meaning":"kind; type; measure word","note":"一種顏色 is one kind of color. 種 counts kinds; the object itself keeps its own counting word. 禾 is beside 重."},
};
