// Isolated display metadata; does not register main-course introductions.
export const extraCharacterInfo:Record<string,{pinyin:string;meaning:string;note:string}>={
'恤':{pinyin:'xù',meaning:'T-shirt character',note:'Recognize 恤 after the Latin T in T恤. 忄 is the heart radical on the left; 血 is on the right. The garment word is the full T恤, not 恤 alone.'},
'件':{pinyin:'jiàn',meaning:'measure word for garments',note:'Use 件 for individual garments such as 襯衫 and 外套. 亻 is on the left; 牛 is on the right.'},
'襯':{pinyin:'chèn',meaning:'shirt character; lining',note:'The first character in 襯衫. 衤 is the clothing radical on the left; 親 is on the right.'},
'衫':{pinyin:'shān',meaning:'shirt; light upper garment',note:'The second character in 襯衫. Notice the clothing radical 衤 on the left and three diagonal strokes 彡 on the right.'},
'外':{pinyin:'wài',meaning:'outside; outer',note:'In 外套, 外 points to an outer layer. Notice 夕 on the left and 卜 on the right.'},
'套':{pinyin:'tào',meaning:'cover; set; coat character',note:'Learn 外套 as the full word for an outer garment. 大 sits at the top of 套.'},
'毛':{pinyin:'máo',meaning:'hair; wool',note:'In 毛衣, part of the word for a sweater. The bent final stroke distinguishes 毛 from 手.'},
'衣':{pinyin:'yī',meaning:'clothing',note:'The full character 衣 can become the clothing radical 衤 on the left of 褲, 裙, and 襪.'},
'褲':{pinyin:'kù',meaning:'trousers',note:'The first character in 褲子. 衤 signals clothing; 庫 is on the right.'},
'子':{pinyin:'zǐ',meaning:'child; noun suffix',note:'子 is neutral-tone zi in 褲子, 裙子, 鞋子, 襪子, 帽子, 橘子, and 梨子. Its standalone reading is zǐ.'},
'條':{pinyin:'tiáo',meaning:'measure word for long items',note:'Use 條 with 褲子 and 裙子 here. Notice the wood component 木 in the lower right.'},
'裙':{pinyin:'qún',meaning:'skirt',note:'The first character in 裙子. 衤 is the clothing radical; 君 is on the right.'},
'洋':{pinyin:'yáng',meaning:'ocean; dress character',note:'In Taiwan, 洋裝 means a dress. 氵 is on the left; 羊 is on the right. Learn the full clothing word.'},
'裝':{pinyin:'zhuāng',meaning:'dress; clothing; equip',note:'The second character in 洋裝. Look for 衣 in the bottom part.'},
'鞋':{pinyin:'xié',meaning:'shoe',note:'The first character in 鞋子. 革 is on the left; two stacked 土 shapes form 圭 on the right.'},
'雙':{pinyin:'shuāng',meaning:'pair; double',note:'Use 雙 for a pair of shoes or socks. The repeated 隹 shapes at the top help you remember two.'},
'襪':{pinyin:'wà',meaning:'sock',note:'The first character in 襪子. The clothing radical 衤 is on the left; 蔑 is on the right.'},
'帽':{pinyin:'mào',meaning:'hat; cap',note:'The first character in 帽子. 巾 is on the left; 冒 is on the right.'},
'頂':{pinyin:'dǐng',meaning:'top; measure word for hats',note:'Use 頂 for hats and caps. 丁 is on the left; 頁 is on the right.'},
'蘋':{pinyin:'píng',meaning:'apple character',note:'The first character in 蘋果. 艹 at the top marks a plant-related character; 頻 sits underneath.'},
'果':{pinyin:'guǒ',meaning:'fruit; result',note:'Shared by 蘋果 and 芒果. Notice the box-shaped upper part over 木.'},
'個':{pinyin:'gè',meaning:'general measure word',note:'A common counting word for whole fruit. Often pronounced lightly as ge in counting phrases. 亻 is on the left; 固 is on the right.'},
'香':{pinyin:'xiāng',meaning:'fragrant',note:'The first character in 香蕉. 禾 sits above 日.'},
'蕉':{pinyin:'jiāo',meaning:'banana character',note:'The second character in 香蕉. 艹 sits above 焦; notice 灬 at the bottom.'},
'根':{pinyin:'gēn',meaning:'root; measure word for long items',note:'Use 根 for an individual banana here. 木 is on the left; 艮 is on the right.'},
'橘':{pinyin:'jú',meaning:'mandarin orange; tangerine',note:'The first character in 橘子. 木 is on the left; 矞 is on the right.'},
'葡':{pinyin:'pú',meaning:'grape character',note:'The first character in 葡萄. 艹 is at the top; 匍 is underneath. Learn 葡萄 as one fruit word.'},
'萄':{pinyin:'táo',meaning:'grape character',note:'The second character in 葡萄. 艹 is at the top; 匋 is underneath.'},
'串':{pinyin:'chuàn',meaning:'string; bunch; measure word',note:'Use 串 for a bunch of grapes. A vertical stroke runs through two box shapes: think of items joined on a string.'},
'西':{pinyin:'xī',meaning:'west',note:'In 西瓜, part of the established word for watermelon. Learn the complete fruit word; it does not mean a western fruit.'},
'瓜':{pinyin:'guā',meaning:'melon; gourd',note:'Shared by 西瓜 and 木瓜. Keep the central and outer strokes distinct.'},
'鳳':{pinyin:'fèng',meaning:'phoenix; pineapple character',note:'The first character in the Taiwan word 鳳梨. Notice the outer frame and bird-shaped interior.'},
'梨':{pinyin:'lí',meaning:'pear',note:'梨子 is pear; 鳳梨 is pineapple. 利 sits above 木. The meaning depends on the full word.'},
'芒':{pinyin:'máng',meaning:'mango character; awn',note:'The first character in 芒果. 艹 sits above 亡.'},
'草':{pinyin:'cǎo',meaning:'grass',note:'The first character in 草莓. 艹 sits above 早.'},
'莓':{pinyin:'méi',meaning:'berry',note:'The second character in 草莓. 艹 sits above 每.'},
'顆':{pinyin:'kē',meaning:'measure word for small round items',note:'Use 顆 for strawberries or individual grapes. 果 is on the left; 頁 is on the right. A whole bunch of grapes uses 串.'},
'木':{pinyin:'mù',meaning:'tree; wood',note:'The first character in 木瓜, papaya. Also appears as a component in 梨 and 橘.'},
};
