-- Register optional lessons and preserve reviewed earlier completion bounds.
-- Append-only tails keep existing partial step indexes and completed credit.
insert into hanzi_private.lesson_lengths as existing (lesson_id, steps, historical_steps) values
  ('extra-clothing-learn-1', 38, ARRAY[11]::integer[]),
  ('extra-clothing-learn-2', 28, ARRAY[8]::integer[]),
  ('extra-clothing-learn-3', 22, ARRAY[8]::integer[]),
  ('extra-clothing-images', 18, ARRAY[9]::integer[]),
  ('extra-clothing-measures', 38, ARRAY[20]::integer[]),
  ('extra-clothing-listening', 20, ARRAY[11]::integer[]),
  ('extra-clothing-review', 30, ARRAY[21]::integer[]),
  ('extra-fruits-learn-1', 41, ARRAY[11]::integer[]),
  ('extra-fruits-learn-2', 28, ARRAY[8]::integer[]),
  ('extra-fruits-learn-3', 22, ARRAY[8]::integer[]),
  ('extra-fruits-images', 18, ARRAY[9]::integer[]),
  ('extra-fruits-measures', 38, ARRAY[20]::integer[]),
  ('extra-fruits-listening', 20, ARRAY[11]::integer[]),
  ('extra-fruits-review', 30, ARRAY[21]::integer[]),
  ('extra-practice-恤', 4, ARRAY[]::integer[]),
  ('extra-practice-件', 4, ARRAY[]::integer[]),
  ('extra-practice-襯', 4, ARRAY[]::integer[]),
  ('extra-practice-衫', 4, ARRAY[]::integer[]),
  ('extra-practice-外', 4, ARRAY[]::integer[]),
  ('extra-practice-套', 4, ARRAY[]::integer[]),
  ('extra-practice-毛', 4, ARRAY[]::integer[]),
  ('extra-practice-衣', 4, ARRAY[]::integer[]),
  ('extra-practice-褲', 4, ARRAY[]::integer[]),
  ('extra-practice-子', 4, ARRAY[]::integer[]),
  ('extra-practice-條', 4, ARRAY[]::integer[]),
  ('extra-practice-裙', 4, ARRAY[]::integer[]),
  ('extra-practice-洋', 4, ARRAY[]::integer[]),
  ('extra-practice-裝', 4, ARRAY[]::integer[]),
  ('extra-practice-鞋', 4, ARRAY[]::integer[]),
  ('extra-practice-雙', 4, ARRAY[]::integer[]),
  ('extra-practice-襪', 4, ARRAY[]::integer[]),
  ('extra-practice-帽', 4, ARRAY[]::integer[]),
  ('extra-practice-頂', 4, ARRAY[]::integer[]),
  ('extra-practice-蘋', 4, ARRAY[]::integer[]),
  ('extra-practice-果', 4, ARRAY[]::integer[]),
  ('extra-practice-個', 4, ARRAY[]::integer[]),
  ('extra-practice-香', 4, ARRAY[]::integer[]),
  ('extra-practice-蕉', 4, ARRAY[]::integer[]),
  ('extra-practice-根', 4, ARRAY[]::integer[]),
  ('extra-practice-橘', 4, ARRAY[]::integer[]),
  ('extra-practice-葡', 4, ARRAY[]::integer[]),
  ('extra-practice-萄', 4, ARRAY[]::integer[]),
  ('extra-practice-串', 4, ARRAY[]::integer[]),
  ('extra-practice-西', 4, ARRAY[]::integer[]),
  ('extra-practice-瓜', 4, ARRAY[]::integer[]),
  ('extra-practice-鳳', 4, ARRAY[]::integer[]),
  ('extra-practice-梨', 4, ARRAY[]::integer[]),
  ('extra-practice-芒', 4, ARRAY[]::integer[]),
  ('extra-practice-草', 4, ARRAY[]::integer[]),
  ('extra-practice-莓', 4, ARRAY[]::integer[]),
  ('extra-practice-顆', 4, ARRAY[]::integer[]),
  ('extra-practice-木', 4, ARRAY[]::integer[])
on conflict (lesson_id) do update
set steps=excluded.steps,
 historical_steps=ARRAY(select distinct n from unnest(existing.historical_steps || excluded.historical_steps || case when existing.steps <> excluded.steps then ARRAY[existing.steps] else '{}'::integer[] end) n where n > 0 and n <= excluded.steps order by n);
