begin;

create table if not exists public.hanzi_push_subscriptions (
  endpoint text primary key,
  user_id text not null,
  p256dh text not null,
  auth text not null,
  enabled boolean not null default true,
  streak_reminders boolean not null default true,
  encouragement boolean not null default true,
  sentence_checks boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_sent_at timestamptz,
  last_streak_day date,
  last_encouragement_at timestamptz,
  last_sentence_at timestamptz,
  last_sentence_id text,
  failure_count integer not null default 0,
  constraint hanzi_push_user_check check (user_id ~ '^account-v1-[a-f0-9]{64}$'),
  constraint hanzi_push_endpoint_check check (endpoint ~ '^https://.{10,2048}$'),
  constraint hanzi_push_p256dh_check check (p256dh ~ '^[A-Za-z0-9_-]{40,200}$'),
  constraint hanzi_push_auth_check check (auth ~ '^[A-Za-z0-9_-]{10,100}$'),
  constraint hanzi_push_failure_count_check check (failure_count >= 0)
);

create index if not exists hanzi_push_subscriptions_enabled
  on public.hanzi_push_subscriptions(enabled, updated_at desc)
  where enabled;

alter table public.hanzi_push_subscriptions enable row level security;
revoke all on public.hanzi_push_subscriptions from public, anon, authenticated;
grant select, insert, update, delete on public.hanzi_push_subscriptions to service_role;

create table if not exists public.hanzi_push_config (
  id smallint primary key default 1,
  vapid_public_key text not null,
  vapid_private_key text not null,
  subject text not null default 'mailto:hanzi-steps@users.noreply.github.com',
  updated_at timestamptz not null default now(),
  constraint hanzi_push_config_singleton check (id = 1)
);

alter table public.hanzi_push_config enable row level security;
revoke all on public.hanzi_push_config from public, anon, authenticated;
grant select, insert, update on public.hanzi_push_config to service_role;

create table if not exists public.hanzi_push_log (
  id bigint generated by default as identity primary key,
  user_id text not null,
  kind text not null,
  sentence_id text,
  sent_at timestamptz not null default now(),
  constraint hanzi_push_log_user_check check (user_id ~ '^account-v1-[a-f0-9]{64}$'),
  constraint hanzi_push_log_kind_check check (kind in ('streak','encouragement','sentence'))
);

create index if not exists hanzi_push_log_user_sent
  on public.hanzi_push_log(user_id, sent_at desc);

alter table public.hanzi_push_log enable row level security;
revoke all on public.hanzi_push_log from public, anon, authenticated;
grant select, insert, delete on public.hanzi_push_log to service_role;
grant usage, select on sequence public.hanzi_push_log_id_seq to service_role;

create or replace function public.hanzi_push_read(expected_account text, expected_endpoint text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  account_key text := hanzi_private.resolve_account(expected_account);
  result jsonb;
begin
  if account_key is null then
    raise exception 'Sign in to manage notifications.' using errcode = '28000';
  end if;

  select jsonb_build_object(
    'enabled', s.enabled,
    'streakReminders', s.streak_reminders,
    'encouragement', s.encouragement,
    'sentenceChecks', s.sentence_checks
  )
  into result
  from public.hanzi_push_subscriptions s
  where s.user_id = account_key and s.endpoint = expected_endpoint;

  return coalesce(result, 'null'::jsonb);
end
$$;

create or replace function public.hanzi_push_upsert(
  expected_account text,
  push_subscription jsonb,
  push_preferences jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  account_key text := hanzi_private.resolve_account(expected_account);
  v_endpoint text;
  v_p256dh text;
  v_auth text;
  v_streak boolean;
  v_encouragement boolean;
  v_sentence boolean;
begin
  if account_key is null then
    raise exception 'Sign in to manage notifications.' using errcode = '28000';
  end if;

  if jsonb_typeof(push_subscription) is distinct from 'object'
    or jsonb_typeof(push_preferences) is distinct from 'object'
    or octet_length(push_subscription::text) > 6000
    or octet_length(push_preferences::text) > 1000 then
    raise exception 'Invalid notification settings.' using errcode = '22023';
  end if;

  v_endpoint := push_subscription->>'endpoint';
  v_p256dh := push_subscription#>>'{keys,p256dh}';
  v_auth := push_subscription#>>'{keys,auth}';

  if v_endpoint is null or v_endpoint !~ '^https://.{10,2048}$'
    or v_p256dh is null or v_p256dh !~ '^[A-Za-z0-9_-]{40,200}$'
    or v_auth is null or v_auth !~ '^[A-Za-z0-9_-]{10,100}$' then
    raise exception 'Invalid push subscription.' using errcode = '22023';
  end if;

  if jsonb_typeof(push_preferences->'streakReminders') is distinct from 'boolean'
    or jsonb_typeof(push_preferences->'encouragement') is distinct from 'boolean'
    or jsonb_typeof(push_preferences->'sentenceChecks') is distinct from 'boolean' then
    raise exception 'Invalid notification preferences.' using errcode = '22023';
  end if;

  v_streak := (push_preferences->>'streakReminders')::boolean;
  v_encouragement := (push_preferences->>'encouragement')::boolean;
  v_sentence := (push_preferences->>'sentenceChecks')::boolean;

  insert into public.hanzi_push_subscriptions as existing(
    endpoint, user_id, p256dh, auth, enabled,
    streak_reminders, encouragement, sentence_checks, updated_at, failure_count
  )
  values(
    v_endpoint, account_key, v_p256dh, v_auth, true,
    v_streak, v_encouragement, v_sentence, now(), 0
  )
  on conflict(endpoint) do update
    set user_id = excluded.user_id,
        p256dh = excluded.p256dh,
        auth = excluded.auth,
        enabled = true,
        streak_reminders = excluded.streak_reminders,
        encouragement = excluded.encouragement,
        sentence_checks = excluded.sentence_checks,
        updated_at = now(),
        failure_count = 0;

  return jsonb_build_object(
    'enabled', true,
    'streakReminders', v_streak,
    'encouragement', v_encouragement,
    'sentenceChecks', v_sentence
  );
end
$$;

create or replace function public.hanzi_push_disable(expected_account text, expected_endpoint text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  account_key text := hanzi_private.resolve_account(expected_account);
begin
  if account_key is null then
    raise exception 'Sign in to manage notifications.' using errcode = '28000';
  end if;

  update public.hanzi_push_subscriptions
  set enabled = false, updated_at = now()
  where user_id = account_key and endpoint = expected_endpoint;

  return jsonb_build_object('enabled', false);
end
$$;

create or replace function public.hanzi_push_public_key()
returns text
language sql
stable
security definer
set search_path = ''
as $
  select vapid_public_key from public.hanzi_push_config where id = 1
$;

revoke all on function public.hanzi_push_public_key() from public, anon, authenticated;
grant execute on function public.hanzi_push_public_key() to anon, authenticated, service_role;

revoke all on function public.hanzi_push_read(text,text) from public, anon, authenticated;
grant execute on function public.hanzi_push_read(text,text) to anon, authenticated, service_role;

revoke all on function public.hanzi_push_upsert(text,jsonb,jsonb) from public, anon, authenticated;
grant execute on function public.hanzi_push_upsert(text,jsonb,jsonb) to anon, authenticated, service_role;

revoke all on function public.hanzi_push_disable(text,text) from public, anon, authenticated;
grant execute on function public.hanzi_push_disable(text,text) to anon, authenticated, service_role;

commit;
